<?php

namespace instance98
{
	$npcinfo_instance98 = array
		( 
		1 => array
			(
			'mode' => 3,
			'num' => 1,
			'pass' => 'bra',
			'club' => 0,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 2,
			'skills'=>array('401'=>'3','400'=>'6','459'=>'0','461'=>'1','462'=>'0'),
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'f',
			'pls' => 0,
			'mhp' => 7500,
			'msp' => 4000,
			'att' => 750,
			'def' => 750,
			'lvl' => 75,
			'skill' => 1111,
			'money' => 9999,
			'arb' => '奥术战甲B - 炎',
			'arbk' => 'DBPS',
			'arbe' => 3000,
			'arbs' => 3000,
			'arbsk' => '^01098Ab',
			'arh' => '奥术战甲H - 炎',
			'arhk' => 'DHPS',
			'arhe' => 1444,
			'arhs' => 3000,
			'arhsk' => '^01098',
			'arf' => '奥术战甲F - 炎',
			'arfk' => 'DFPS',
			'arfe' => 1444,
			'arfs' => 3000,
			'arfsk' => '^01098',
			'ara' => '奥术战甲A - 炎',
			'arak' => 'DAPS',
			'arae' => 1444,
			'aras' => 3000,
			'arask' => '^01098',
			'art' => '龙虎旗帜',
			'artk' => 'A',
			'arte' => 1000,
			'arts' => 1000,
			'artsk' => 'H',
			'sub' => array
			(
				0 => array
				(
				'name' => '看起来像是红暮的女性',
				'icon' => 7,
				'wep' => '燃素加农炮『爆炎』MK-II',
				'wepk' => 'WG',
				'wepe' => 1280,
				'weps' => 999,
				'wepsk' => 'rfnN',
				'itm1' => '沸腾之血',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				'itm2' => '黑色碎片',
				'itmk2' => 'Y',
				'itme2' => 1,
				'itms2' => 1,
				'description' => '红杀将军 看起来像是红暮的女性，坐镇于无月之影的BOSS（？）。 <span class="linen b">"……红暮真可爱呀，我是说真正的红暮。"</span>',
				),
			),
		),
		2 => array
		(
		'mode' => 2,
		'num' => 16,
		'pass' => 'bra',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teampass' => '',
		'pls' => 99,
		'mhp' => 4000,
		'msp' => 200,
		'att' => 250,
		'def' => 350,
		'lvl' => 45,
		'skill' => 175,
		'money' => 3200,
		'arb' => 'SSS战队校服',
		'arbk' => 'DB',
		'arbe' => 450,
		'arbs' => 100,
		'arh' => '鼓舞士气的头带',
		'arhk' => 'DH',
		'arhe' => 175,
		'arhs' => 100,
		'arf' => '橙黄学生鞋',
		'arfk' => 'DF',
		'arfe' => 175,
		'arfs' => 100,
		'ara' => '广播装置手表α',
		'arak' => 'DA',
		'arae' => 175,
		'aras' => 100,
		'art' => 'ACFUN的账号',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'sub' => array
			(
			0 => array
			  (
			'name' => '水濑 名雪-改',
			'icon' => 11,
			'gd' => 'f',
			'mss' => 50,
			'wep' => '雪兔【复制品】',
			'wepk' => 'WD',
			'wepe' => 300,
			'weps' => 200,
			'wepsk' => 'id',
			'itm1' => '水濑 名雪的半身像',
			'itmk1' => 'WP',
			'itme1' => 33,
			'itms1' => 2,
			'itmsk1' => 'r',
			'itm2' => '草莓圣代',
			'itmk2' => 'MH',
			'itme2' => 27,
			'itms2' => 2,
			'description' => '全息幻象 水濑 名雪-改，手持优秀的爆系武器，当然你也可以当成是掉落。顺便也会掉生命增加的药物。',
			),
		1 => array
			(
			'name' => '立华 奏-改',
			'icon' => 12,
			'gd' => 'f',
			'mss' => 50,
			'wep' => 'GS【HandSonic Ver.4】',
			'wepk' => 'WP',
			'wepe' => 300,
			'weps' => 300,
			'wepsk' => 'ZN',
			'itm1' => '立华 奏的半身像',
			'itmk1' => 'WP',
			'itme1' => 33,
			'itms1' => 2,
			'itmsk1' => 'r',
			'itm3' => 'Angel Player',
			'itmk3' => 'HM',
			'itme3' => 30,
			'itms3' => 2,
			'itm4' => 'GS【HandSonic Ver.2】',
			'itmk4' => 'WK',
			'itme4' => 200,
			'itms4' => 300,
			'itmsk4' => 'kj',
			'description' => '全息幻象 立华 奏-改，手持优秀的殴系武器，当然你也可以当成是掉落。顺便也会掉增加歌魂的道具。',
			),
		2 => array
			(
			'name' => '思念体-海马 濑人',
			'icon' => 13,
			'gd' => 'm',
			'wep' => '【逆转的女神】',
			'wepk' => 'WC',
			'wepe' => 350,
			'weps' => 300,
			'wepsk' => 'N',
			'itm1' => '游戏王卡包',
			'itmk1' => 'ygo',
			'itme1' => 1,
			'itms1' => 7,
			'itm2' => '传说的白磨刀石',
			'itmk2' => 'Y',
			'itme2' => 60,
			'itms2' => 12,
			'itm3' => '《抽卡术》',
			'itmk3' => 'VV',
			'itme3' => 66,
			'itms3' => 1,
			'itmsk3' => '',
			'description' => '全息幻象 思念体-海马 濑人，手持优秀的投系武器，当然你也可以当成是掉落。顺便也会掉卡包、磨刀石与全系熟练书籍。',
			),
		3 => array
			(
			'name' => '思念体-触手众',
			'icon' => 14,
			'gd' => 'm',
			'wep' => '触手的力量',
			'wepk' => 'WG',
			'wepe' => 300,
			'weps' => 300,
			'wepsk' => 'N',
			'itm1' => '妖精的羽翼',
			'itmk1' => 'A',
			'itme1' => 1,
			'itms1' => 1,
			'itmsk1' => 'q',
			'itm2' => '艾莲娜的圣钉',
			'itmk2' => 'Y',
			'itme2' => 45,
			'itms2' => 20,
			'itm3' => '斗技【神砂风暴】',
			'itmk3' => 'WF',
			'itme3' => 340,
			'itms3' => 300,
			'itm4' => '触手的知识',
			'itmk4' => 'ME',
			'itme4' => 28,
			'itms4' => 2,
			'description' => '全息幻象 思念体-触手众，手持令制作死神的玩家们为之疯狂的武器，当然你也可以当成是掉落。顺便教导你一些触手的知识。',
			),
		),
	),
	
			5 => array
			(
			'mode' => 2,
			'num' => 2,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'rage' => 150,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'pls' => 99,
			'mhp' => 6666,
			'msp' => 333,
			'att' => 333,
			'def' => 333,
			'lvl' => 66,
			'skill' => 233,
			'money' => 3333,
			'arb' => '杏仁豆腐模样的以太结晶',
			'arbk' => 'DB',
			'arbe' => 666,
			'arbs' => 666,
			'arbsk' => 'A',
			'arh' => '杏仁豆腐模样的狙击镜片',
			'arhk' => 'DH',
			'arhe' => 666,
			'arhs' => 666,
			'arhsk' => 'cW',
			'arf' => '杏仁豆腐模样的长筒靴',
			'arfk' => 'DF',
			'arfe' => 666,
			'arfs' => 666,
			'arfsk' => 'qE',
			'ara' => '杏仁豆腐模样的童话伪翼',
			'arak' => 'DA',
			'arae' => 666,
			'aras' => 666,
			'arask' => 'UI',
			'art' => '杏仁豆腐模样的HP制御系统',
			'artk' => 'A',
			'arte' => 666,
			'arts' => 666,
			'artsk' => 'H',
			'itm1' => '杏仁豆腐的ID卡',
			'itmk1' => 'Z',
			'itme1' => 1,
			'itms1' => 1,
			'sub' => array
			(
			0 => array
				(
				'name' => '看起来像是冴月麟的生物',
				'icon' => 3,
				'gd' => 'f',
				'club' => 9,
				'mss' => 30,
				'wep' => '【生まれたての风】模样的杏仁豆腐',
				'wepk' => 'WF',
				'wepe' => 500,
				'weps' => 100,
				'wepsk' => 'd',
				'itm2' => '《红魔乡设定废案》',
				'itmk2' => 'VS',
				'itme2' => 1,
				'itms2' => 1,
				'itmsk2' => '246',
				'itm3' => '《ぼくのフレンド》',
				'itmk3' => 'ss',
				'itme3' => 110,
				'itms3' => 1,
				'itmsk3' => '',
				'itm4' => '简称为UCW的杏仁豆腐',
				'itmk4' => 'ME',
				'itme4' => 24,
				'itms4' => 3,
				'itmsk4' => 'z',
				'description' => '杏仁豆腐 看起来像是冴月麟的生物，对于可恶的触手们来说，可以说基本就等于一本隐形技能书！……但现在情况可大不同了！',
				),
			1 => array
				(
				'name' => '看起来像是某四面的生物',
				'icon' => 4,
				'gd' => 'm',
				'club' => 8,
				'wep' => '【连续凤凰】模样的杏仁豆腐',
				'wepk' => 'WG',
				'wepe' => 500,
				'weps' => 60,
				'wepsk' => 'd',
				'itm2' => '安雅人体冰雕',
				'itmk2' => 'Y',
				'itme2' => 1,
				'itms2' => 1,
				'itmsk2' => '',
				'itm3' => '深生态杏仁豆腐',
				'itmk3' => 'ME',
				'itme3' => 24,
				'itms3' => 3,
				'itmsk3' => 'z',
				'description' => '杏仁豆腐 看起来像是某四面的生物，对于可恶的触手们来说，可以说基本就等于一个安雅！……但现在情况可大不同了！',
				),
			),
		),
		
		6 => array
			(
			'mode' => 2,
			'num' => 1,
			'pass' => 'bra',
			'club' => 0,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 4,
			'tactic' => 3,
			'skills'=>array('461'=>'1'),
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'r',
			'pls' => 99,
			'mhp' => 8888,
			'msp' => 400,
			'att' => 400,
			'def' => 777,
			'lvl' => 45,
			'skill' => 477,
			'money' => 17777,
			'arb' => '【强袭型属性防御装甲】',
			'arbk' => 'DB',
			'arbe' => 888,
			'arbs' => 444,
			'arbsk' => 'a',
			'arh' => '【强袭型冲击防御头盔】',
			'arhk' => 'DH',
			'arhe' => 888,
			'arhs' => 444,
			'arhsk' => 'A',
			'arf' => '【强袭型数据护膝】',
			'arfk' => 'DF',
			'arfe' => 888,
			'arfs' => 444,
			'arfsk' => 'R',
			'ara' => '【强袭型陷阱拦截护盾】',
			'arak' => 'DA',
			'arae' => 888,
			'aras' => 444,
			'arask' => 'm',
			'art' => '【ACFUN的荣耀】',
			'artk' => 'Ag',
			'arte' => 5000,
			'arts' => 500,
			'artsk' => 'H',
			'sub' => array
			(
				0 => array
				(
				'name' => '看起来像是西林的猴子',
				'icon' => 2,
				'mss' => 100,
				'wep' => '【全屏幕弹幕发射】',
				'wepk' => 'WG',
				'wepe' => 360,
				'weps' => 600,
				'wepsk' => 'Nrew',
				'itm1' => '■DeathNote■',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				'itm2' => 'TDG压片猴',
				'itmk2' => 'Y',
				'itme2' => 1,
				'itms2' => 1,
				'description' => '黑幕 看起来像是西林的猴子，对玩家具有很大威胁，如果防御值没有达到2000最好不要惹他（她）。掉落可以杀死任意一名玩家的道具“死亡笔记”，和大量的金钱。',
				),
			),
		),
		
		
		9 => array
			(
			'mode' => 3,
			'num' => 1,
			'pass' => 'bra',
			'club' => 17,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 99,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'f',
			'pls' => 26,
			'mhp' => 10000000,
			'msp' => 4000,
			'att' => 200000,
			'def' => 4000,
			'lvl' => 97,
			'skill' => 2400,
			'money' => 1,
			'arb' => '奥术战甲B - 霜',
			'arbk' => 'DBPS',
			'arbe' => 6000,
			'arbs' => 1400,
			'arbsk' => '^01098Aa',
			'arh' => '奥术战甲H - 霜',
			'arhk' => 'DHPS',
			'arhe' => 4000,
			'arhs' => 1300,
			'arhsk' => '^01098',
			'arf' => '奥术战甲F - 霜',
			'arfk' => 'DFPS',
			'arfe' => 4000,
			'arfs' => 1300,
			'arfsk' => '^01098',
			'ara' => '奥术战甲A - 霜',
			'arak' => 'DAPS',
			'arae' => 4000,
			'aras' => 1300,
			'arask' => '^01098',
			'art' => '龙虎徽标',
			'artk' => 'A',
			'arte' => 200,
			'arts' => 300,
			'artsk' => 'Hc',
			'sub' => array
			(
				0 => array
				(
				'name' => '看起来像是蓝凝的女性',
				'mss' => 40,
				'skills' => array('406'=>'0','432'=>'0','459'=>'0','461'=>'1'),
				'icon' => 52,
				'wep' => '『AZURE RONDO』',
				'wepk' => 'WKF',
				'wepe' => 2000,
				'weps' => 360,
				'wepsk' => 'rkd',
				'itm1' => '被冰封的结晶',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				'description' => '坐镇于冰封墓场的NPC，几乎无敌的存在……但好像因为姐姐的到来变得乖巧一点了……？<span class="yellow b">没事还是不要惹她好了……</span>',
				),
			),
		),
		
		
		11 => array
			(
			'mode' => 1,
			'num' => 7,
			'pass' => 'bra',
			'club' => 0,
			'bid' => 0,
			'inf' => '',
			'rage' => 88,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'r',
			'pls' => 99,
			'mhp' => 2888,
			'msp' => 888,
			'att' => 88,
			'def' => 88,
			'lvl' => 30,
			'skill' => 100,
			'money' => 888,
			'arb' => '职人的佩服',
			'arbk' => 'DB',
			'arbe' => 888,
			'arbs' => 888,
			'arbsk' => 'a',
			'arh' => '职人的搞头',
			'arhk' => 'DH',
			'arhe' => 888,
			'arhs' => 888,
			'arhsk' => 'DF',
			'arf' => '职人的满足',
			'arfk' => 'DF',
			'arfe' => 888,
			'arfs' => 888,
			'ara' => '职人的拿手',
			'arak' => 'DA',
			'arae' => 888,
			'aras' => 888,
			'arask' => 'H',
			'art' => '职人的荣耀',
			'artk' => 'A',
			'arte' => 888,
			'arts' => 888,
			'artsk' => 'c',
			'sub' => array
			(
				0 => array
				(
				'name' => 'Hank',
				'icon' => 91,
				'mss' => 100,
				'wep' => '『性感玉米』',
				'wepk' => 'WD',
				'wepe' => 88,
				'weps' => 888,
				'wepsk' => 'ewuip',
				'itm1' => '我打败HANK了！',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				'description' => '真职人 Hank，使用带有全属性的爆系武器，掉落极优秀的防具。',
				),
				
				1 => array
				(
				'name' => '爱情上甘岭',
				'icon' => 92,
				'mss' => 100,
				'wep' => '『阿里嘎头哦～』',
				'wepk' => 'WK',
				'wepe' => 88,
				'weps' => 888,
				'wepsk' => 'ewuip',
				'itm1' => '我成功TDGSGL了！',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				'description' => '真职人 爱情上甘岭，使用带有全属性的斩系武器，掉落极优秀的防具。',
				),
				
				2 => array
				(
				'name' => '221',
				'icon' => 94,
				'mss' => 100,
				'wep' => '『和谐你全家』',
				'wepk' => 'WP',
				'wepe' => 88,
				'weps' => 888,
				'wepsk' => 'uiewp',
				'arb' => '神之装束',
				'arbk' => 'DB',
				'arbe' => 888,
				'arbs' => 888,
				'arbsk' => 'a',
				'arh' => '神之远见',
				'arhk' => 'DH',
				'arhe' => 888,
				'arhs' => 888,
				'arhsk' => 'DF',
				'arf' => '神之步伐',
				'arfk' => 'DF',
				'arfe' => 888,
				'arfs' => 888,
				'ara' => '神之操控',
				'arak' => 'DA',
				'arae' => 888,
				'aras' => 888,
				'arask' => 'H',
				'art' => '神之荣耀',
				'artk' => 'A',
				'arte' => 888,
				'arts' => 888,
				'artsk' => 'c',
				'itm1' => '荼荼丸的茶',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				'description' => '真职人 221，使用带有全属性的殴系武器，掉落极优秀的防具。',
				
				),
				3 => array
				(
				'name' => 'Erul Tron',
				'icon' => 93,
				'club' => 0,
				'mss' => 70,
				'wep' => '『罗德不列颠号』',
				'wepk' => 'WC',
				'wepe' => 88,
				'weps' => 888,
				'wepsk' => 'uiewp',
				'arb' => '少女的泳衣',
				'arbk' => 'DB',
				'arbe' => 888,
				'arbs' => 888,
				'arbsk' => 'a',
				'arh' => '少女的单马尾',
				'arhk' => 'DH',
				'arhe' => 888,
				'arhs' => 888,
				'arhsk' => 'DF',
				'arf' => '少女的高筒靴',
				'arfk' => 'DF',
				'arfe' => 888,
				'arfs' => 888,
				'ara' => '少女的绒边手套',
				'arak' => 'DA',
				'arae' => 888,
				'aras' => 888,
				'arask' => 'H',
				'art' => '少女的星星眼',
				'artk' => 'A',
				'arte' => 888,
				'arts' => 888,
				'artsk' => 'c',
				'itm1' => '罗德不列颠号舰长钥匙',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				'description' => '真职人 Erul Tron，使用带有全属性的射系武器，掉落极优秀的防具。',
				),
				
				4 => array
				(
				'name' => '亚玛丽欧·维拉蒂安',
				'icon' => 95,
				'club' => 0,
				'mss' => 50,
				'wep' => '负人气的光环',
				'wepk' => 'WP',
				'wepe' => 88,
				'weps' => 888,
				'wepsk' => 'uiewp',
				'arb' => '阿婆主的点击量',
				'arbk' => 'DB',
				'arbe' => 888,
				'arbs' => 888,
				'arbsk' => 'a',
				'arh' => '阿婆主的点击量',
				'arhk' => 'DH',
				'arhe' => 888,
				'arhs' => 888,
				'arhsk' => 'DF',
				'arf' => '阿婆主的点击量',
				'arfk' => 'DF',
				'arfe' => 888,
				'arfs' => 888,
				'ara' => '阿婆主的点击量',
				'arak' => 'DA',
				'arae' => 888,
				'aras' => 888,
				'arask' => 'H',
				'art' => '阿婆主的点击量',
				'artk' => 'A',
				'arte' => 888,
				'arts' => 888,
				'artsk' => 'c',
				'itm1' => '点击量终于爆表了！',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				'itm2' => '负人品的结界',
				'itmk2' => 'WG',
				'itme2' => 88,
				'itms2' => 88,
				'itmsk2' => 'kN',
				'description' => '真职人 亚玛丽欧·维拉蒂安，使用带有全属性的殴系武器，掉落极优秀的防具。',
				),
				
				5 => array
				(
				'name' => '便当盒',
				'icon' => 100,
				'gd' => 'f',
				'club' => 17,
				'lvl' => 1,
				'mhp' => 8888888,
				'skills'=>array('401'=>'5','461'=>'1'),
				'skill' => 20,
				'def' => 88888,
				'wep' => '灭罪「正直者の死」',
				'wepk' => 'WF',
				'wepe' => 8,
				'weps' => 888,
				'wepsk' => 'r',
				'arb' => '吉祥物',
				'arbk' => 'DB',
				'arbe' => 1,
				'arbs' => 10000,
				'arbsk' => 'Aa',
				'arh' => '吉祥物',
				'arhk' => 'DH',
				'arhe' => 1,
				'arhs' => 10000,
				'arhsk' => '',
				'arf' => '吉祥物',
				'arfk' => 'DF',
				'arfe' => 1,
				'arfs' => 10000,
				'ara' => '吉祥物',
				'arak' => 'DA',
				'arae' => 1,
				'aras' => 10000,
				'arask' => '',
				'art' => '姬露瑞希的爱心便当',
				'artk' => 'A',
				'arte' => 1,
				'arts' => 1,
				'artsk' => 'Bb',
				'description' => '真职人 便当盒，ACFUN大逃杀吉祥物，卖萌的存在，拥有888万点HP和双抹消饰品，几乎无法杀死。',
				),
				
				6 => array
				(
				'name' => 'KHIBIKI《黑曲》',
				'mode'=>'3',
				'gd' => 'f',
				'icon' => 113,
				'mss' => 30,
				'club' => 17,
				'lvl' => 1,
				'mhp' => 6666666,
				'skills'=>array('415'=>'1','461'=>'1'),
				'skill' => 20,
				'def' => 20,
				'wep' => '武裝幻想『DAYDREAM』',
				'wepk' => 'WG',
				'wepe' => 8,
				'weps' => 888,
				'wepsk' => 'r',
				'arb' => '【純黑色的連帽型外套】',
				'arbk' => 'DB',
				'arbe' => 1,
				'arbs' => 10000,
				'arbsk' => 'Aa',
				'arh' => '【純黑色的耳罩式耳機】',
				'arhk' => 'DH',
				'arhe' => 1,
				'arhs' => 10000,
				'arhsk' => '',
				'arf' => '【純黑色的皮製型長靴】',
				'arfk' => 'DF',
				'arfe' => 1,
				'arfs' => 10000,
				'ara' => '【純黑色的電子式繪筆】',
				'arak' => 'DA',
				'arae' => 1,
				'aras' => 10000,
				'arask' => '',
				'art' => '黑色終曲『HONOUR』',
				'artk' => 'A',
				'arte' => 1,
				'arts' => 1,
				'artsk' => 'Zz',
				'description' => '真职人 黑色夺魂曲，ACFUN大逃杀吉祥物，卖萌的存在，似乎很难对其造成伤害。',
				),
			),
		),
		
		14 => array(
		'mode' => 1,
		'num' => 3,
		'pass' => 'bra',
		'club' => 99,
		'bid' => 0,
		'inf' => '',
		'state' => 1,
		'rage' => 5,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'f',
		'pls' => 99,
		'mhp' => 2800,
		'msp' => 400,
		'att' => 75,
		'def' => 75,
		'lvl' => 20,
		'skill' => 25,
		'money' => 3,
		'sub' => array
		(
			0 => array
			(
			'name' => '讲解员 梦美',
			'icon' => 61,
			'mss' => 50,
			'wep' => '垃圾花束',
			'wepk' => 'WP',
			'wepe' => 175,
			'weps' => 36,
			'wepsk' => 'c',
			'arb' => '接待员制服',
			'arbk' => 'DB',
			'arbe' => 75,
			'arbs' => 50,
			'arbsk' => 'a',
			'arh' => '橙色信号缎带',
			'arhk' => 'DH',
			'arhe' => 640,
			'arhs' => 50,
			'arf' => '蓝色信号缎带',
			'arfk' => 'DF',
			'arfe' => 640,
			'arfs' => 50,
			'ara' => '绿色信号缎带',
			'arak' => 'DA',
			'arae' => 640,
			'aras' => 50,
			'art' => '星空之愿',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
			'description' => '数据碎片 讲解员 梦美，<span class="yellow b">被击杀后会变身为攻击力极强的NPC</span>。',
			),
			1 => array
			(
			'name' => '喧哗少女 叶留佳',
			'icon' => 63,
			'mss' => 50,
			'wep' => '七色玻璃珠',
			'wepk' => 'WK',
			'wepe' => 160,
			'weps' => 36,
			'wepsk' => 'ec',
			'arb' => 'RF高校校服',
			'arbk' => 'DB',
			'arbe' => 75,
			'arbs' => 50,
			'arbsk' => 'a',
			'arh' => '粉红双球发饰',
			'arhk' => 'DH',
			'arhe' => 640,
			'arhs' => 50,
			'arf' => '女式皮鞋',
			'arfk' => 'DF',
			'arfe' => 640,
			'arfs' => 50,
			'ara' => '奇怪的袋子',
			'arak' => 'DA',
			'arae' => 640,
			'aras' => 50,
			'art' => '友情之愿',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
			'description' => '数据碎片 喧哗少女 叶留佳，<span class="yellow b">被击杀后会变身为攻击力极强的NPC</span>。',
			),
			2 => array
			(
			'name' => '风纪委员 静流',
			'icon' => 65,
			'mss' => 50,
			'wep' => '银白口哨',
			'wepk' => 'WF',
			'wepe' => 175,
			'weps' => 200,
			'wepsk' => 'c',
			'arb' => '风祭学院校服',
			'arbk' => 'DB',
			'arbe' => 75,
			'arbs' => 50,
			'arbsk' => '',
			'arh' => '白色眼罩',
			'arhk' => 'DH',
			'arhe' => 640,
			'arhs' => 50,
			'arf' => '女式运动鞋',
			'arfk' => 'DF',
			'arfe' => 640,
			'arfs' => 50,
			'ara' => 'Mp3播放器',
			'arak' => 'DA',
			'arae' => 640,
			'aras' => 50,
			'art' => '平和之愿',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
			'description' => '数据碎片 风纪委员 静流，<span class="yellow b">被击杀后会变身为攻击力极强的NPC</span>。',
			),
		),
	), 
	
		20 => array
		(
		'mode' => 2,
		'num' => 10,
		'pass' => 'gbauibg2',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 88,
		'pose'=> 1,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'r',
		'pls' => 98,
		'mhp' => 6000,
		'msp' => 400,
		'att' => 200,
		'def' => 200,
		'lvl' => 120,
		'skill' => 600,
		'money' => 800,
		'arb' => '英熊战甲B',
		'arbk' => 'DBPS',
		'arbe' => 2000,
		'arbs' => 1300,
		'arbsk' => '^01098A',
		'arh' => '英熊战甲H',
		'arhk' => 'DHPS',
		'arhe' => 1600,
		'arhs' => 1300,
		'arhsk' => '^01098DF',
		'arf' => '英熊战甲F',
		'arfk' => 'DFPS',
		'arfe' => 1500,
		'arfs' => 1300,
		'arfsk' => '^01098a',
		'ara' => '英熊战甲A',
		'arak' => 'DAPS',
		'arae' => 1600,
		'aras' => 1300,
		'arask' => '^01098H',
		'art' => '熊之力',
		'artk' => 'A',
		'arte' => 9,
		'arts' => 9,
		'artsk' => 'c',
		'sub' => array
		(
			0 => array
			(
			'name' => '霜火协奏曲',
			'icon' => 0,
			'club' => 6,
			'wep' => '『看吧，你的死兆星正在天上闪耀！』',
			'wepk' => 'WC',
			'wepe' => 333,
			'weps' => 600,
			'wepsk' => 'w',
			),
			1 => array
			(
			'name' => '脸骑士-菜包',
			'club' => 98,
			'icon' => 0,
			'wep' => '脸',
			'wepk' => 'WP',
			'wepe' => 300,
			'weps' => 600,
			'wepsk' => 'N',
			),
			2 => array
			(
			'name' => '枪毙的某神',
			'icon' => 0,
			'club' => 3,
			'wep' => '《小黄的时间球》',
			'wepk' => 'WC',
			'wepe' => 180,
			'weps' => 600,
			'wepsk' => 'r',
			),
			3 => array
			(
			'name' => '我是高达',
			'icon' => 0,
			'club' => 8,
			'wep' => '毒性凸眼鱼',
			'wepk' => 'WF',
			'wepe' => 200,
			'weps' => 600,
			'wepsk' => 'pd',
			),
			4 => array
			(
			'name' => '一旦接受这种设定',
			'icon' => 0,
			'club' => 10,
			'wep' => '『一瞬千击』',
			'wepk' => 'WP',
			'wepe' => 190,
			'weps' => 600,
			'wepsk' => 'r',
			),
			5 => array
			(
			'name' => '一方通行',
			'icon' => 0,
			'club' => 9,
			'wep' => '【矢量操作】',
			'wepk' => 'WG',
			'wepe' => 300,
			'weps' => 600,
			'wepsk' => 'N',
			),
			6 => array
			(
			'name' => '晓魂之歌',
			'icon' => 0,
			'club' => 2,
			'wep' => '锋利的电气毒性晓魂之歌-改[+4]',
			'wepk' => 'WK',
			'wepe' => 300,
			'weps' => 600,
			'wepsk' => 'pew',
			),
			7 => array
			(
			'name' => '卡',
			'icon' => 0,
			'club' => 13,
			'wep' => '【不屈的意志】',
			'wepk' => 'WF',
			'wepe' => 140,
			'weps' => 600,
			'wepsk' => 'r',
			),
			8 => array
			(
			'name' => 'Exocet',
			'icon' => 0,
			'club' => 9,
			'wep' => '『微型火箭加速噴射單輪車』',
			'wepk' => 'WP',
			'wepe' => 110,
			'weps' => 600,
			'wepsk' => 'ru',
			),
			9 => array
			(
			'name' => '中西醫',
			'icon' => 0,
			'club' => 1,
			'wep' => '《衷中參西錄》',
			'wepk' => 'WP',
			'wepe' => 250,
			'weps' => 600,
			'wepsk' => 'p',
			),
			10 => array
			(
			'name' => '黑猫',
			'icon' => 0,
			'club' => 6,
			'wep' => '阔剑地雷吸附器',
			'wepk' => 'WP',
			'wepe' => 400,
			'weps' => 600,
			'wepsk' => 'Mm',
			),
			11 => array
			(
			'name' => '水羊',
			'icon' => 0,
			'club' => 2,
			'wep' => '■Darthnote■',
			'wepk' => 'WK',
			'wepe' => 400,
			'weps' => 600,
			'wepsk' => 'c',
			),
			12 => array
			(
			'name' => '上帝的左手',
			'icon' => 0,
			'club' => 2,
			'wep' => '胡来的左手',
			'wepk' => 'WK',
			'wepe' => 270,
			'weps' => 600,
			'wepsk' => 'd',
			),
			13 => array
			(
			'name' => '半人半灵半吊子',
			'icon' => 0,
			'club' => 98,
			'wep' => '楼观剑',
			'wepk' => 'WK',
			'wepe' => 200,
			'weps' => 600,
			'wepsk' => 'd',
			'itm1' => '白楼剑',
			'itmk1' => 'WK',
			'itme1' => 130,
			'itms1' => 600,
			'itmsk1' => 'r',
			),
			14 => array
			(
			'name' => '死亡荆棘',
			'icon' => 0,
			'club' => 7,
			'wep' => '【荆棘式电子地雷】',
			'wepk' => 'WK',
			'wepe' => 210,
			'weps' => 600,
			'wepsk' => 'd',
			),
			15 => array
			(
			'name' => '超魔理沙-电子',
			'icon' => 0,
			'club' => 14,
			'wep' => '【荆棘式电子地雷】',
			'wepk' => 'WP',
			'wepe' => 240,
			'weps' => 600,
			'wepsk' => 'd',
			),
			16 => array
			(
			'name' => '东方地雷殿',
			'icon' => 0,
			'club' => 7,
			'wep' => '【荆棘式电子地雷】',
			'wepk' => 'WD',
			'wepe' => 210,
			'weps' => 600,
			'wepsk' => 'd',
			),
			17 => array
			(
			'name' => 'fossil',
			'icon' => 0,
			'club' => 1,
			'wep' => '大钉棍棒',
			'wepk' => 'WP',
			'wepe' => 250,
			'weps' => 600,
			'wepsk' => 'Nn',
			),
			18 => array
			(
			'name' => '流风之念',
			'icon' => 0,
			'club' => 4,
			'wep' => '连击烧输尿管~☆',
			'wepk' => 'WG',
			'wepe' => 150,
			'weps' => 600,
			'wepsk' => 'ru',
			),
			19 => array
			(
			'name' => 'MESSIAH',
			'icon' => 0,
			'club' => 4,
			'wep' => '本格的嘴炮',
			'wepk' => 'WG',
			'wepe' => 240,
			'weps' => 600,
			'wepsk' => 'd',
			),
			20 => array
			(
			'name' => '帕秋莉诺蕾姬',
			'icon' => 0,
			'club' => 9,
			'wep' => '水&火符「Phlogistic Rain」',
			'wepk' => 'WF',
			'wepe' => 260,
			'weps' => 600,
			'wepsk' => 'ui',
			),
			21 => array
			(
			'name' => '坂田铜时',
			'icon' => 0,
			'club' => 1,
			'wep' => '无毁的受王拳',
			'wepk' => 'WP',
			'wepe' => 380,
			'weps' => 600,
			),
			22 => array
			(
			'name' => '耶和华',
			'icon' => 0,
			'club' => 15,
			'wep' => 'L5爆发！',
			'wepk' => 'WF',
			'wepe' => 250,
			'weps' => 600,
			'wepsk' => 'd',
			),
			23 => array
			(
			'name' => '闹球肾',
			'icon' => 0,
			'club' => 1,
			'wep' => '一个半角符号',
			'wepk' => 'WF',
			'wepe' => 150,
			'weps' => 600,
			'wepsk' => 'rd',
			),
			24 => array
			(
			'name' => '初音ミク',
			'icon' => 0,
			'club' => 4,
			'wep' => '「Falchion Rider」模样的杏仁豆腐',
			'wepk' => 'WG',
			'wepe' => 190,
			'weps' => 600,
			'wepsk' => 'r',
			'arb' => '英雄战甲B模样的杏仁豆腐',
			'arh' => '英雄战甲H模样的杏仁豆腐',
			'arf' => '英雄战甲F模样的杏仁豆腐',
			'ara' => '英雄战甲A模样的杏仁豆腐',
			'art' => '英雄之力模样的杏仁豆腐',
			),
			25 => array
			(
			'name' => 'Abyss混沌',
			'icon' => 0,
			'club' => 1,
			'wep' => '混乱邪恶之塔',
			'wepk' => 'WF',
			'wepe' => 1,
			'weps' => 1,
			'wepsk' => 'r',
			),
			26 => array
			(
			'name' => '飞雪大大',
			'icon' => 0,
			'club' => 9,
			'wep' => '魔王の剑',
			'wepk' => 'WK',
			'wepe' => 300,
			'weps' => 300,
			'wepsk' => 'u',
			),
			27 => array
			(
			'name' => '微笑的疯子',
			'icon' => 0,
			'club' => 1,
			'wep' => '把妹の手',
			'wepk' => 'WP',
			'wepe' => 100,
			'weps' => 600,
			'wepsk' => 'Nnr',
			),
			28 => array
			(
			'name' => '挂机中的灰尘',
			'icon' => 0,
			'club' => 9,
			'wep' => '★挂机の萌力★',
			'wepk' => 'WF',
			'wepe' => 250,
			'weps' => 600,
			'wepsk' => 'ni',
			),
			29 => array
			(
			'name' => '西园寺世界酱',
			'icon' => 0,
			'club' => 5,
			'wep' => '节操炸弹G',
			'wepk' => 'WD',
			'wepe' => 300,
			'weps' => 600,
			'wepsk' => 'id',
			),
			30 => array
			(
			'name' => '索非亚小傻鸟',
			'icon' => 0,
			'club' => 8,
			'wep' => 'COCO☆酱',
			'wepk' => 'WC',
			'wepe' => 280,
			'weps' => 600,
			'wepsk' => 'lu',
			),
			31 => array
			(
			'name' => '浮云_小坏',
			'icon' => 0,
			'club' => 9,
			'wep' => '向日葵妖精',
			'wepk' => 'WG',
			'wepe' => 251,
			'weps' => 600,
			'wepsk' => 'ud',
			'itm1' => 'YES♂SIR',
			'itmk1' => 'Z',
			'itme1' => 1,
			'itms1' => 1,
			),
			32 => array
			(
			'name' => '人形蚂蚁α',
			'icon' => 0,
			'club' => 9,
			'wep' => '纸条■■■■',
			'wepk' => 'WC',
			'wepe' => 280,
			'weps' => 600,
			'wepsk' => 'Ne',
			),
			33 => array
			(
			'name' => 'tabris',
			'icon' => 0,
			'club' => 13,
			'wep' => '十二试炼',
			'wepk' => 'WC',
			'wepe' => 400,
			'weps' => 600,
			'wepsk' => 'r',
			),
			34 => array
			(
			'name' => '吔姐蕉',
			'icon' => 0,
			'club' => 1,
			'wep' => '无毁的受王拳',
			'wepk' => 'WP',
			'wepe' => 410,
			'weps' => 600,
			),
			35 => array
			(
			'name' => 'ad53123426',
			'icon' => 0,
			'club' => 9,
			'wep' => '无毁的受王拳',
			'wepk' => 'WP',
			'wepe' => 530,
			'weps' => 600,
			),
		),
	),
	
	21 => array
		(
		'mode' => 2,
		'num' => 8,
		'pass' => 'wei42bg',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 250,
		'pose'=> 2,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'r',
		'pls' => 97,
		'mhp' => 12900,
		'msp' => 800,
		'att' => 4000,
		'def' => 4000,
		'lvl' => 165,
		'skill' => 800,
		'money' => 40000,
		'arb' => '黑熊的武神战甲B',
		'arbk' => 'DBPS',
		'arbe' => 4000,
		'arbs' => 1200,
		'arbsk' => '^01098Aa',
		'arh' => '黑熊的武神战甲H',
		'arhk' => 'DHPS',
		'arhe' => 2500,
		'arhs' => 1200,
		'arhsk' => '^01098b',
		'arf' => '黑熊的武神战甲F',
		'arfk' => 'DFPS',
		'arfe' => 2500,
		'arfs' => 1200,
		'arfsk' => '^01098B',
		'ara' => '黑熊的武神战甲A',
		'arak' => 'DAPS',
		'arae' => 2500,
		'aras' => 1200,
		'arask' => '^01098H',
		'art' => '武神之魂',
		'artk' => 'A',
		'arte' => 9,
		'arts' => 9,
		'artsk' => 'ch',
		'sub' => array
		(
			2 => array
			(
			'name' => '披着黑熊皮的水月',
			'gd' => 'f',
			'icon' => 99,
			'club' => 9,
			'mode' => 2,
			'mhp' => 14000,
			'skill' => 1200,
			'skills' => array('81'=>'0', '461'=>'1', '403'=>'3'),
			'wep' => '「饭纲权现降临」',
			'wepk' => 'WC',
			'wepe' => 1,
			'weps' => 9999,
			'wepsk' => 'Bbx',
			'art' => '《Dead Sea Scrolls》',
			'artk' => 'Ah',
			'arte' => 3000,
			'arts' => 233,
			'artsk' => 'cx',
			'itm1' => 'EX黑&金符『St. R.M.T wii be BANED』',
			'itmk1' => 'WF',
			'itme1' => 1200,
			'itms1' => '∞',
			'itmsk1' => 'nrdk',
			'itm2' => 'Barrett M95',
			'itmk2' => 'WJ',
			'itme2' => 1500,
			'itms2' => 500,
			'itmsk2' => 'nfS',
			'itm3' => '圣光啊!你有看到那个敌人吗！',
			'itmk3' => 'Z',
			'itme3' => 1,
			'itms3' => 1,
			'description' => '武神 披着黑熊皮的水月，以<span class="yellow b">英灵殿中的四天王之一</span>为蓝本，疑似为模因工厂（？）制作出的复制品。<br>在记忆中所向无敌的火金符已经被时代所淘汰了，所以他换了一个。',
			),
			3 => array
			(
			'name' => '芬里爾《黑熊》',
			'gd' => 'f',
			'mode' => 3,
			'icon' => 104,
			'club' => 18,
			'mhp' => 10000,
			'att' => 100,
			'def' => 400,
			'rage' => 10,
			'lvl' => 20, 
			'skill' => 100,
			'skills' => array('461'=>'1', '403'=>'3'),
			'wep' => '黑熊武神斩',
			'wepk' => 'WK',
			'wepe' => 200,
			'weps' => 100,
			'wepsk' => '',
			'arb' => '黑熊装备B',
			'arbk' => 'DB',
			'arbe' => 400,
			'arbs' => 300,
			'arbsk' => 'zh',
			'arh' => '黑熊装备H',
			'arhk' => 'DH',
			'arhe' => 233,
			'arhs' => 300,
			'arhsk' => 'z',
			'arf' => '黑熊装备F',
			'arfk' => 'DF',
			'arfe' => 233,
			'arfs' => 300,
			'arfsk' => 'z',
			'ara' => '黑熊装备A',
			'arak' => 'DA',
			'arae' => 233,
			'aras' => 300,
			'arask' => 'z',
			'art' => '黑熊装备T',
			'artk' => 'Ah',
			'arte' => 233,
			'arts' => 233,
			'artsk' => 'zv',
			'description' => '武神 芬里爾《黑熊》，以<span class="yellow b">英灵殿吉祥物</span>为蓝本，疑似为模因工厂（？）制作出的复制品。<br>她没有第二形态，但你应该不会因此而轻视她。',
			),
			4 => array
			(
			'name' => '披着黑熊皮的北京推倒你',
			'gd' => 'm',
			'icon' => 102,
			'club' => 14,
			'skill' => 6000,
			'skills' => array('461'=>'1', '403'=>'3'),
			'wep' => '拳头',
			'wepk' => 'WN',
			'wepe' => 800,
			'weps' => 998,
			'wepsk' => 'hrden',
			'itm1' => '肉○器“北京”型',
			'itmk1' => 'WP',
			'itme1' => 4000,
			'itms1' => '∞',
			'itmsk1' => 'g',
			'description' => '武神 披着黑熊皮的北京推倒你，以<span class="yellow b">英灵殿小黑熊</span>为蓝本，疑似为模因工厂（？）制作出的复制品。<br>是一位孤高的拳法家……然而并没有意义！',
			),
			5 => array
			(
			'name' => '披着黑熊皮的BorisX',
			'gd' => 'm',
			'icon' => 105,
			'hp' => 9400,
			'club' => 4,
			'skill' => 1150,
			'skills' => array('461'=>'1', '403'=>'3'),
			'wep' => 'AKM改二',
			'wepk' => 'WJ',
			'wepe' => 2600,
			'weps' => 4000,
			'wepsk' => 'n',
			'description' => '武神 披着黑熊皮的BorisX，以<span class="yellow b">英灵殿四天王之一</span>为蓝本，疑似为模因工厂（？）制作出的复制品。<br>他没有花哨的属性，但这不妨碍他击倒你。',
			),
			6 => array
			(
			'name' => '披着黑熊皮的Renamon',
			'gd' => 'f',
			'mhp' => 14000,
			'icon' => 98,
			'club' => 2,
			'skill' => 1100,
			'skills' => array('461'=>'1', '403'=>'3'),
			'wep' => '画(ping)笔(ru)',
			'wepk' => 'WK',
			'wepe' => 3500,
			'weps' => 999,
			'wepsk' => 'rdn',
			'description' => '武神 披着黑熊皮的Renamon，以<span class="yellow b">英灵殿阿卡林</span>为蓝本，疑似为模因工厂（？）制作出的复制品。<br>不是（）是（）……？',
			),
			7 => array
			(
			'name' => '披着黑熊皮的beijuzhu',
			'gd' => 'm',
			'icon' => 0,
			'club' => 7,
			'skill' => 3000,
			'skills' => array('461'=>'1', '403'=>'3'),
			'wep' => '破解的PSP-3000',
			'wepk' => 'WP',
			'wepe' => 3100,
			'weps' => 999,
			'wepsk' => 'rne',
			'description' => '武神 披着黑熊皮的beijuzhu，以<span class="yellow b">英灵殿阿卡林</span>为蓝本，疑似为模因工厂（？）制作出的复制品。<br>你处在眩晕状态中，无法动弹！',
			),
			8 => array
			(
			'name' => '披着黑熊皮的捂脸姬',
			'gd' => 'f',
			'pose' => 4,
			'att' => 4000,
			'icon' => 0,
			'club' => 8,
			'skill' => 850,
			'skills' => array('461'=>'1', '403'=>'3'),
			'wep' => '超级☆无敌辰音LILY',
			'wepk' => 'WD',
			'wepe' => 15000,
			'weps' => 999,
			'wepsk' => 'cdn',
			'description' => '武神 披着黑熊皮的捂脸姬，以<span class="yellow b">英灵殿阿卡林</span>为蓝本，疑似为模因工厂（？）制作出的复制品。<br>她很强，但大概没有你强。',
			),
			9 => array
			(
			'name' => '披着黑熊皮的Yoshiko-G',
			'gd' => 'f',
			'def' => 30250,
			'icon' => 4,
			'club' => 18,
			'skill' => 900,
			'skills' => array('461'=>'1', '403'=>'3'),
			'wep' => '光翼型近接支援残酷戦闘機銃',
			'wepk' => 'WG',
			'wepe' => 4000,
			'weps' => 999,
			'wepsk' => 'nre',
			'description' => '武神 披着黑熊皮的Yoshiko-G，以<span class="yellow b">英灵殿阿卡林</span>为蓝本，疑似为模因工厂（？）制作出的复制品。<br>他和这座大殿一样，被埋在历史的尘埃中。',
			),
		),
	),
		22 => array
		(
		'mode' => 1,
		'num' => 3,
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 255,
		'pose'=> 4,
		'tactic' => 3,
		'killnum' => 99,
		'teamID' => '',
		'teamPass' => '',
		'pls' => 96,
		'mhp' => 23333,
		'msp' => 2333,
		'def' => 2333,
		'lvl' => 197,
		'skill' => 444,
		'money' => 100000,
		'arb' => '黑熊的威光',
		'arbk' => 'DB',
		'arbe' => 6000,
		'arbs' => 400,
		'arbsk' => 'ab',
		'arh' => '黑熊的极光',
		'arhk' => 'DH',
		'arhe' => 4000,
		'arhs' => 300,
		'arhsk' => 'h',
		'arf' => '黑熊的霞光',
		'arfk' => 'DF',
		'arfe' => 4000,
		'arfs' => 300,
		'arfsk' => 'A',
		'ara' => '黑熊的寒光',
		'arak' => 'DA',
		'arae' => 4000,
		'aras' => 300,
		'arask' => 'c',
		'art' => '黑熊的曙光',
		'artk' => 'A',
		'arte' => 200,
		'arts' => 300,
		'artsk' => 'H',
		'sub' => array
		(
			0 => array
			(
			'name' => '冴月麟 - 黑熊特化版',
			'gd' => 'f',
			'icon' => 3,
			'club' => 9,
			'mss' => 50,
			'att' => 23333,
			'skill' => array('wp' => 1600, 'wk' => 2300, 'wc' => 2700, 'wg' => 1900, 'wd' => 1500, 'wf' => 2800),
			'skills' => array('81' => '0', '461'=>'1', '403'=>'3'),
			'wep' => '键 希望弹',
			'wepk' => 'WC',
			'wepe' => 50000,
			'weps' => 998,
			'wepsk' => 'zdfkc',
			'arb' => '真 - 桔黄色的大衣',
			'arh' => '真 - 红色的发圈',
			'arf' => '真 - 橙黄学生鞋',
			'ara' => '真 - 带翅膀的书包',
			'art' => '真 - 奇迹之愿',
			'itm1' => '键 燃烧弹',
			'itmk1' => 'WF',
			'itme1' => 48000,
			'itms1' => '∞',
			'itmsk1' => 'Nfzr',
			'itm2' => '键 生命弹',
			'itmk2' => 'WG',
			'itme2' => 50000,
			'itms2' => 998,
			'itmsk2' => 'zdrfk',
			'itm3' => '键 未来弹',
			'itmk3' => 'WP',
			'itme3' => 50000,
			'itms3' => '∞',
			'itmsk3' => 'rcdfN',
			'itm5' => '键 旅途弹',
			'itmk5' => 'WK',
			'itme5' => 50000,
			'itms5' => 998,
			'itmsk5' => 'zdNkc',
			'itm6' => '键 审判弹',
			'itmk6' => 'WF',
			'itme6' => 100000,
			'itms6' => '∞',
			'itmsk6' => 'nrfkx',
			),
			1 => array
			(
			'name' => '黑熊殿四面BOSS',
			'gd' => 'm',
			'icon' => 163,
			'club' => 18,
			'att' => 233,
			'mhp' => 4444,
			'skill' => 120,
			'skills' => array('461'=>'1'),
			'wep' => '【黑暗童话】',
			'wepk' => 'WJ',
			'wepe' => 1,
			'weps' => 9999,
			'wepsk' => 'rdpn',
			'arb' => '可爱标记拼成的披风',
			'arh' => '天马经理的面罩',
			'arf' => '刀锋般的后腿',
			'ara' => '研究员的笔记本',
			'art' => 'S.M.I.L.E.!',
			'itm2' => '四面的腿',
			'itmk2' => 'PB2',
			'itme2' => 1,
			'itms2' => 1,
			'itmsk2' => 'x',
			'itm1' => '武器师安雅的奖赏',
			'itmk1' => 'Y',
			'itme1' => 1,
			'itms1' => 3,
			'itmsk1' => 'z',
			),
			2 => array
			(
			'name' => '黑色熊猫人 lemon',
			'gd' => 'r',
			'icon' => 162,
			'club' => 7,
			'lvl' => 0,
			'rage' => 0,
			'mhp' => 9800,
			'att' => 32767,
			'def' => 32767,
			'skill' => 1150,
			'skills'=>array('412'=>'0','461'=>'1', '403'=>'3'),	//反演233
			'wep' => '电气火绳枪',
			'wepk' => 'WG',
			'wepe' => 30,
			'weps' => 60,
			'wepsk' => 'en',
			'arb' => '工作装',
			'arh' => '防灾头巾',
			'ara' => '垫肩',
			'arf' => '钉鞋',
			'art' => 'Untainted Glory',
			'itm1' => 'ACDTS Farming Helper',
			'itmk1' => 'ME',
			'itme1' => 20,
			'itms1' => 200,
			'itmsk1' => 'z',
			),
		),
	),
	
	45=> array
		(
		'mode' => 2,
		'num' => 8,
		'pass' => 'bra',
		'club' => 14,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'skills' => array('404'=>'2'),
		'pose'=> 4,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => 'MhHmpsz',
		'teamPass' => 'Eb2Lfz3Usvui',
		'pls' => 99,
		'mhp' => 5400,
		'msp' => 200,
		'att' => 200,
		'def' => 300,
		'lvl' => 55,
		'skill' => 220,
		'money' => 4500,
		'mss' => 50,
		'arb' => '电波的意志',
		'arbk' => 'DB',
		'arbe' => 550,
		'arbs' => 100,
		'arh' => '智者的头脑',
		'arhk' => 'DH',
		'arhe' => 550,
		'arhs' => 100,
		'ara' => '触手的潜能',
		'arak' => 'DA',
		'arae' => 550,
		'aras' => 100,
		'arask' => 'R',
		'arf' => '头名的尊严',
		'arfk' => 'DF',
		'arfe' => 550,
		'arfs' => 100,
		'art' => '你沒戲唱了，快去死吧！',
		'artk' => 'A',
		'arte' => 200,
		'arts' => 10,
		'artsk' => 'xa',
		'sub' => array
		(
		0 => array
			(
			'name' => '索菲亚小傻鸟模样的虚名',
			'gd' => 'm',
			'icon' => 109,
			'wep' => '燃烧吧',
			'wepk' => 'WG',
			'wepe' => 40,
			'weps' => 20000,
			'wepsk' => 'Au',
			'itm1' => '傻鸟的结婚请柬',
			'itmk1' => 'WC',
			'itme1' => 600,
			'itms1' => 150,
			'itmsk1' => 'rdc',
			'itm2' => '红烧小鸟',
			'itmk2' => 'HB',
			'itme2' => 500,
			'itms2' => 150,
			'itm3' => '悲叹之种',
			'itmk3' => 'DB',
			'itme3' => 500,
			'itms3' => 150,
			'itmsk3' => 'PF',
			'description' => '电波幽灵 索菲亚小傻鸟，电波第一代触手代表。另一个身份是A岛美食版女神kitty酱。因为响应了玩家内心的祈愿，变成了虚名的形状。',
			),
		1 => array
			(
			'name' => '悲叹之种模样的虚名',
			'gd' => 'm',
			'icon' => 110,
			'wep' => '片翼虚影',
			'wepk' => 'WK',
			'wepe' => 15,
			'weps' => 100,
			'wepsk' => 'Ad',
			'itm1' => '虚名的精灵片翼',
			'itmk1' => 'WK',
			'itme1' => 600,
			'itms1' => 150,
			'itmsk1' => 'uid',
			'itm2' => '不明黑色物质',
			'itmk2' => 'HB',
			'itme2' => 500,
			'itms2' => 150,
			'itm3' => '悲叹之种',
			'itmk3' => 'DH',
			'itme3' => 500,
			'itms3' => 150,
			'itmsk3' => 'KG',
			'description' => '电波幽灵 悲叹之种模样的虚名，电波第二代触手代表。本命武器为精灵片翼。最受大家喜爱的NPC，但到底喜欢的是什么你们都懂得。',
			),
		2 => array
			(
			'name' => 'YS模样的虚名',
			'gd' => 'm',
			'icon' => 111,
			'wep' => '毁灭阴影',
			'wepk' => 'WF',
			'wepe' => 80,
			'weps' => 150,
			'wepsk' => 'Ac',
			'itm1' => 'YS的魂之挽歌',
			'itmk1' => 'WF',
			'itme1' => 600,
			'itms1' => 20,
			'itmsk1' => 'd',
			'itm2' => '奶酪',
			'itmk2' => 'HB',
			'itme2' => 500,
			'itms2' => 150,
			'itm3' => '悲叹之种',
			'itmk3' => 'DA',
			'itme3' => 500,
			'itms3' => 150,
			'itmsk3' => 'CD',
			'description' => '电波幽灵 YS模样的虚名，电波第三代触手代表。是一名脸很黑的小学生。因为响应了玩家内心的祈愿，变成了虚名的形状。',
			),
		3 => array
			(
			'name' => '逆向朝阳模样的虚名',
			'gd' => 'f',
			'icon' => 112,
			'wep' => '大爷星人',
			'wepk' => 'WC',
			'wepe' => 50,
			'weps' => 200,
			'wepsk' => 'AN',
			'itm1' => '朝阳的肥猫大爷',
			'itmk1' => 'WP',
			'itme1' => 600,
			'itms1' => 150,
			'itmsk1' => 'cd',
			'itm2' => '肉用大爷',
			'itmk2' => 'HB',
			'itme2' => 500,
			'itms2' => 150,
			'itm3' => '悲叹之种',
			'itmk3' => 'DF',
			'itme3' => 500,
			'itms3' => 150,
			'itmsk3' => 'a',
			'description' => '电波幽灵 逆向朝阳模样的虚名，电波第二代触手，电波前段时间的统治者。养了很多猫大爷。因为响应了玩家在内心的祈愿，变成了虚名的形状。',
			),
		),
	),
	
		88 => array
			(
			'mode' => 1,
			'num' => 4,
			'pass' => 'bra',
			'club' => 17,
			'bid' => 0,
			'inf' => '',
			'rage' => 188,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 88,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'm',
			'pls' => 32,
			'mhp' => 8888888,
			'msp' => 888,
			'att' => 88888,
			'def' => 88888,
			'lvl' => 88,
			'skill' => 88888,
			'money' => 88888,
			'arb' => '[数据删除]',
			'arbk' => 'DB',
			'arbe' => 8888,
			'arbs' => 8888,
			'arbsk' => 'Aa',
			'arh' => '[数据删除]',
			'arhk' => 'DH',
			'arhe' => 8888,
			'arhs' => 8888,
			'arhsk' => 'Bb',
			'arf' => '[数据删除]',
			'arfk' => 'DF',
			'arfe' => 8888,
			'arfs' => 8888,
			'arfsk' => 'Mm',
			'ara' => '[数据删除]',
			'arak' => 'DA',
			'arae' => 8888,
			'aras' => 8888,
			'arask' => 'Hc',
			'art' => '[数据删除]',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'xH',
			'sub' => array
			(
				0 => array
				(
				'name' => 'SCP-682',
				'icon' => 103,
				'wep' => '[数据删除]',
				'wepk' => 'WN',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				'description' => 'SCP-682，坐镇于SCP研究设施，完全无敌的存在（？），要是不幸被打到的话，必死无疑（？）。最好的避免方法，就是<span class="yellow b">永远不要去SCP研究设施</span>。',
				),
				1 => array
				(
				'name' => 'SCP-173',
				'icon' => 106,
				'wep' => '[数据删除]',
				'wepk' => 'WF',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				'description' => 'SCP-173，坐镇于SCP研究设施，完全无敌的存在（？），要是不幸被打到的话，必死无疑（？）。最好的避免方法，就是<span class="yellow b">永远不要去SCP研究设施</span>。',
				),
				2 => array
				(
				'name' => 'SCP-076',
				'icon' => 107,
				'wep' => '[数据删除]',
				'wepk' => 'WK',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				'description' => 'SCP-076，坐镇于SCP研究设施，完全无敌的存在（？），要是不幸被打到的话，必死无疑（？）。最好的避免方法，就是<span class="yellow b">永远不要去SCP研究设施</span>。',
				),
				3 => array
				(
				'name' => 'SCP-958',
				'icon' => 108,
				'wep' => '[数据删除]',
				'wepk' => 'WG',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				'description' => 'SCP-958，坐镇于SCP研究设施，完全无敌的存在（？），要是不幸被打到的话，必死无疑（？）。最好的避免方法，就是<span class="yellow b">永远不要去SCP研究设施</span>。',
				),
			),
		),
		90 => array
			(
			'mode' => 2,
			'num' => 300,
			'pass' => 'bra',
			'club' => 0,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 0,
			'tactic' => 0,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'r',
			'pls' => 99,
			'mhp' => 1000,
			'msp' => 200,
			'att' => 130,
			'def' => 150,
			'lvl' => 30,
			'skill' => 150,
			'money' => 400,		
			'arb' => '跟风群皮',
			'arbk' => 'DB',
			'arbe' => 135,
			'arbs' => 130,		
			'arbsk' => 'GD',				
			'arh' => '萌豚头像',
			'arhk' => 'DH',
			'arhe' => 125,
			'arhs' => 130,			
			'arf' => '女装丝袜',
			'arfk' => 'DF',
			'arfe' => 125,
			'arfs' => 130,			
			'ara' => '发送按钮',
			'arak' => 'DA',
			'arae' => 125,
			'aras' => 130,			
			'art' => '键盘侠之证',
			'artk' => 'A',
			'arte' => 120,
			'arts' => 110,
			'itm1' => '巧克力饼干',
			'itmk1' => 'HB',
			'itme1' => 250,
			'itms1' => 35,

			'sub' => array
			(
			0 => array
				(
				'name' => '强化的复读机',
				'icon' => 25,
				'wep' => '刷屏之枪',
				'wepk' => 'WG',
				'wepe' => 150,
				'weps' => 150,
				'wepsk' => 'N',
				'itm2' => '偷来的表情包',
				'itmk2' => 'ME',
				'itme2' => 5,
				'itms2' => 1,
				'description' => '“人类的本质就是复读机，但我可以复读2次。”<br>但没有人理他。<br>进化后的杂兵，但还是杂兵，大概作用是能给你提供更多的钱。',
				),
			1 => array
				(
				'name' => '专业的秦国人',
				'icon' => 26,
				'wep' => '无名剑',
				'wepk' => 'WP',
				'wepe' => 250,
				'weps' => 250,
				'wepsk' => 'N',
				'itm2' => '《缓慢剑法》',
				'itmk2' => 'VK',
				'itme2' => 35,
				'itms2' => 1,
				'description' => '“缓-慢-剑-法！”<br>其实他根本不看秦川直播。<br>进化后的杂兵，但还是杂兵，大概作用是能给你提供更多的钱。',
				),
			2 => array
				(
				'name' => '伪装的白学家',
				'icon' => 29,
				'mss' => 30,
				'wep' => '东马小山',
				'wepk' => 'WC',
				'wepe' => 250,
				'weps' => 250,
				'wepsk' => 'N',
				'itm2' => '《我超熟练的》',
				'itmk2' => 'VV',
				'itme2' => 10,
				'itms2' => 1,
				'description' => '“为什么……明明是我先的……”<br>他其实就只会这一句话。<br>进化后的杂兵，但还是杂兵，大概作用是能给你提供更多的钱。',
				),
			3 => array
				(
				'name' => '精巧的膜触党',
				'icon' => 28,
				'wep' => '嘴臭开花',
				'wepk' => 'WF',
				'wepe' => 150,
				'weps' => 150,
				'wepsk' => 'N',
				'itm2' => '余裕！',
				'itmk2' => 'MH',
				'itme2' => 5,
				'itms2' => 1,
				'description' => '“触手爷爷你不得好死啊……！”<br>他终于露出本性了。<br>进化后的杂兵，但还是杂兵，大概作用是能给你提供更多的钱。',
				),
			),
		),
	);

	//campfireMOD新增npc
	$npcinfo_instance98[1005]=array
	(
		'mode' => 2,
		'num' => 16,
		'pass' => 'bra',
		'skills' => array('400'=>'1',),
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'gd' => 'r',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'pls' => 99,
		'mhp' => 2700,
		'msp' => 200,
		'att' => 233,
		'def' => 233,
		'lvl' => 28,
		'skill' => 233,
		'money' => 2200,
		'arb' => '人啊就是不知道',
		'arbk' => 'DB',
		'arbe' => 233,
		'arbs' => 66,
		'arbsk' => 'H',
		'arh' => '自己不可以预料',
		'arhk' => 'DH',
		'arhe' => 66,
		'arhs' => 233,
		'arf' => '当然要靠自我奋斗',
		'arfk' => 'DF',
		'arfe' => 66,
		'arfs' => 233,
		'ara' => '一个人的命运啊',
		'arak' => 'DA',
		'arae' => 66,
		'aras' => 233,
		'art' => '但也要考虑到历史的行程',
		'artk' => 'A',
		'arte' => 66,
		'arts' => 233,
		'sub' => array
		(
		0 => array
			(
			'name' => '死于毒酱包的亡灵',
			'icon' => 10051,
			'wep' => '更改菜谱后的不甜酱包',
			'wepk' => 'WC',
			'wepe' => 168,
			'weps' => 40,
			'wepsk' => 'p',
			'itm1' => '愿天堂没有毒酱包',
			'itmk1' => 'HB',
			'itme1' => 450,
			'itms1' => 120,
			'itm2' => '受潮的军火箱',
			'itmk2' => 'kggb',
			'itme2' => 1,
			'itms2' => 1,
			'itmsk2' => '',
			'itm3' => '受潮的弹药箱',
			'itmk3' => 'kgab',
			'itme3' => 1,
			'itms3' => 4,
			'itmsk3' => '',
			'description' => "迷之怨灵 死于毒酱包的亡灵，在某个平行宇宙中因误食了剧毒酱包而死的可怜人。<br><span class='yellow'>“这是合成了的……咬一口没关系吧……？”</span><br>隔着屏幕都能感觉到从它身上渗透出的怨念……",
			),
		1 => array
			(
			'name' => '死于地雷改造的亡灵',
			'icon' => 10052,
			'wep' => '便携式☆大打击☆',
			'wepk' => 'WD',
			'wepe' => 136,
			'weps' => 40,
			'wepsk' => 'd',
			'itm1' => '我特么才不是傻逼',
			'itmk1' => 'A',
			'itme1' => 233,
			'itms1' => 233,
			'itmsk1' => 'zaH',
			'itm2' => '受潮的军火箱',
			'itmk2' => 'kggb',
			'itme2' => 1,
			'itms2' => 1,
			'itmsk2' => '',
			'itm3' => '受潮的弹药箱',
			'itmk3' => 'kgab',
			'itme3' => 1,
			'itms3' => 4,
			'itmsk3' => '',
			'description' => "迷之怨灵 死于地雷改造的亡灵，在某个平行宇宙中因改造陷阱失误被炸死的可怜人。<br><span class='yellow'>“终于攒够买雷的钱了，等我把它改成爆炸物头名就死定啦！”</span><br>隔着屏幕都能感觉到从它身上渗透出的怨念……",
			),
		2 => array
			(
			'name' => '死于献祭的亡灵',
			'icon' => 10053,
			'wep' => '吸取生命力的结界',
			'wepk' => 'WF',
			'wepe' => 173,
			'weps' => 40,
			'wepsk' => 'w',
			'itm1' => '《怎样提高阅读效率》',
			'itmk1' => 'VV',
			'itme1' => 40,
			'itms1' => 2,
			'itmsk1' => 'x',
			'itm2' => '受潮的军火箱',
			'itmk2' => 'kggb',
			'itme2' => 1,
			'itms2' => 1,
			'itmsk2' => '',
			'itm3' => '受潮的弹药箱',
			'itmk3' => 'kgab',
			'itme3' => 1,
			'itms3' => 4,
			'itmsk3' => '',
			'description' => "迷之怨灵 死于献祭的亡灵，在某个平行宇宙中因被系统坑害而死的可怜人。<br><span class='yellow'>“这么中二的剧情，看不下去啊，直接点就是了……卧槽我怎么死了！？”</span><br>隔着屏幕都能感觉到从它身上渗透出的怨念……",
			),
		3 => array
			(
			'name' => '死于鱼弹袭击的亡灵',
			'icon' => 10054,
			'wep' => '虎纹鲨鱼',
			'wepk' => 'WG',
			'wepe' => 145,
			'weps' => 200,
			'wepsk' => 'i',
			'itm1' => '哇嘎力马死',
			'itmk1' => 'ME',
			'itme1' => 12,
			'itms1' => 4,
			'itmsk1' => 'z',
			'itm2' => '受潮的军火箱',
			'itmk2' => 'kggb',
			'itme2' => 1,
			'itms2' => 1,
			'itmsk2' => '',
			'itm3' => '受潮的弹药箱',
			'itmk3' => 'kgab',
			'itme3' => 1,
			'itms3' => 4,
			'itmsk3' => '',
			'description' => "迷之怨灵 死于鱼弹袭击的亡灵，在某个平行宇宙中因忽然出现的乱七八糟的NPC而死的可怜人。<br><span class='yellow'>“这NPC！之前没见过啊！看起来好蠢啊，摸一下试试……”</span><br>隔着屏幕都能感觉到从它身上渗透出的怨念……",
			),
		),
	);
	$npcinfo_instance98[1006]=array
	(
		'mode' => 2,
		'num' => 1,
		'bid' => 0,
		'inf' => '',
		'rage' => 250,
		'pose'=> 2,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'r',
		'pls' => 95,
		'mhp' => 19970,
		'msp' => 800,
		'att' => 5120,
		'def' => 4000,
		'lvl' => 225,
		'skill' => 8192,
		'money' => 0,
		'sub' => array
		(
			0 => array
			(
			'name' => '黑熊王',
			'gd' => 'r',
			'icon' => 210,
			'club' => 24,
			'skills' => array('1902'=>'0','400'=>'5','401'=>'5','402'=>'2','403'=>'5','489'=>'0','81'=>'0','513'=>'0','207'=>'6'),
			'wep' => '『寻熊者』',
			'wepk' => 'WK',
			'wepe' => 900,
			'weps' => 3500,
			'wepsk' => 'Nnyrd',
			'arb' => '猫的强壮',
			'arbk' => 'DBPS',
			'arbe' => 1919,
			'arbs' => 80001,
			'arbsk' => 'ZA^01098',
			'arh' => '猫的目光',
			'arhk' => 'DHPS',
			'arhe' => 1919,
			'arhs' => 80001,
			'arhsk' => 'ZB^01098',
			'arf' => '猫的矫健',
			'arfk' => 'DFPS',
			'arfe' => 1919,
			'arfs' => 80001,
			'arfsk' => 'Za^01098',
			'ara' => '猫的力量',
			'arak' => 'DAPS',
			'arae' => 1919,
			'aras' => 80001,
			'arask' => 'ZH^01098',
			'art' => '猫之影',
			'artk' => 'Ab',
			'arte' => 1919,
			'arts' => 80001,
			'artsk' => 'Zh',
			'itm1' => '刃镜片',
			'itmk1' => 'WK',
			'itme1' => 114514,
			'itms1' => 5,
			'itmsk1' => 'Nnyk',
			'itm2' => '超重型黑熊列车 古斯塔夫最大炮',
			'itmk2' => 'WG',
			'itme2' => 3000,
			'itms2' => 3000,
			'itmsk2' => 'Nnyrd',
			'itm3' => '《黑熊语录》',
			'itmk3' => 'Y',
			'itme3' => 1,
			'itms3' => 1,
			'itmsk3' => 'Z',
			'description' => '机械降神 黑熊王，曾经阻挡在你面前的，英灵殿中不可逾越的高墙，如今你与它再次相见了。<br><span class="brickred b">它没有你想象中那么强大，但你能打败它吗？</span>',
			),
		),
	);
	$npcinfo_instance98[1007]=array
	(
		'mode' => 2,
		'num' => 3,
		'bid' => 0,
		'inf' => '',
		'rage' => 250,
		'pose'=> 2,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'r',
		'mhp' => 65535,
		'msp' => 800,
		'att' => 5120,
		'def' => 4000,
		'lvl' => 250,
		'skill' => 1919,
		'money' => 0,
		'arb' => 'Warsaw Pact',
		'arbk' => 'DBPT',
		'arbe' => 1919,
		'arbs' => 8000001,
		'arbsk' => 'ZA^01099',
		'arh' => 'De-Stalinization',
		'arhk' => 'DHPT',
		'arhe' => 1919,
		'arhs' => 8000001,
		'arhsk' => 'ZB^01099',
		'arf' => 'Muslim Revolution',
		'arfk' => 'DFPT',
		'arfe' => 1919,
		'arfs' => 8000001,
		'arfsk' => 'Za^01099',
		'ara' => 'Flower Power',
		'arak' => 'DAPT',
		'arae' => 1919,
		'aras' => 8000001,
		'arask' => 'ZH^01099',
		'art' => 'Glasnost',
		'artk' => 'Ab',
		'arte' => 1919,
		'arts' => 8000001,
		'artsk' => 'Zh',
		'sub' => array
		(
			0 => array
			(
			'name' => '斗争',
			'gd' => 'r',
			'icon' => 'campfire_98/red.jpg',
			'pls' => 92,
			'club' => 24,
			'mhp' => 19171025,
			'skills' => array('1905'=>'0','1902'=>'0','1903'=>'0','489'=>'0','401'=>'5','207'=>'6'),
			'wep' => 'WE will BURY YOU',
			'wepk' => 'WK',
			'wepe' => 117,
			'weps' => 1918,
			'wepsk' => 'd',
			'itm1' => '红之怒火',
			'itmk1' => 'Y',
			'itme1' => 1,
			'itms1' => 1,
			'itmsk1' => 'f',
			'description' => '第八识 斗争，她的攻击凶猛刚烈，一切防御手段在她的打击面前都如同薄纸一张，想要不付出任何代价就击倒她是完全不可能的！',
			),
			1 => array
			(
			'name' => '权能',
			'gd' => 'r',
			'icon' => 'campfire_98/blue.jpg',
			'pls' => 94,
			'club' => 18,
			'mhp' => 29925,
			'skills' => array('1905'=>'0','1902'=>'0','403'=>'4','432'=>'0','489'=>'0','508'=>'0','513'=>'0','510'=>'2','50'=>'0','240'=>'0','254'=>'0'),
			'wep' => 'Freedom or Death',
			'wepk' => 'WJ',
			'wepe' => 3,
			'weps' => 177674,
			'wepsk' => 'ny',
			'artk' => 'Ac',
			'itm1' => '蓝之希望',
			'itmk1' => 'Y',
			'itme1' => 1,
			'itms1' => 1,
			'itmsk1' => 'k',
			'description' => '第八识 权能，她的攻击灵动迅捷，如同暴风骤雨般将你淹没，但却未必会杀死你；她的防御同样滴水不漏。面对她时，要做好与她鏖战的心理准备。',
			),
			2 => array
			(
			'name' => '虚妄',
			'gd' => 'r',
			'icon' => 'campfire_98/green.jpg',
			'pls' => 93,
			'club' => 24,
			'mhp' => 111778,
			'skills' => array('1905'=>'0','1902'=>'0','1904'=>'0','1906'=>'0','1907'=>'0','489'=>'0','240'=>'0','508'=>'0','469'=>'0','486'=>'2','1900'=>'0'),
			'wep' => 'Al-kaBah',
			'wepk' => 'WD',
			'wepe' => 2222614,
			'weps' => '∞',
			'wepsk' => 'Nnyrd',
			'itm1' => '绿之顺服',
			'itmk1' => 'Y',
			'itme1' => 1,
			'itms1' => 1,
			'itmsk1' => 'd',
			'description' => '第八识 虚无，她的攻击阴险狡诈，如蚀骨之蛇攀附于你的脊背，你必须寻找合适的手段尽快将她击倒，不然她将给你带来永无止境的麻烦——在战斗中、或是战场之外……',
			),
		),
	);
}

?>