<?php

namespace addnpc
{
	$npcinit = array
		(
			'name' => '',	'pass' => 'bra', 'gd' => 'm',	'icon' => 0,	'club' => 0,	
			'mhp' => 0,	'msp' => 0,	'att' => 0,	'def' => 0,	'pls' => 0,	'lvl' => 0,
			'money' => 0,	'inf' => '',	'rage' => 0,	'pose' => 0,	'tactic' => 0,	
			'killnum' => 0,	'npckillnum' => 0, 'state' => 1,	'teamID' => '',	'teamPass' => '','bid' => 0,
			'wep' => '',	'wepk' => '',	'wepe' => 0,	'weps' => 0,	'wepsk' => '',
			'arb' => '',	'arbk' => '',	'arbe' => 0,	'arbs' => 0,	'arbsk' => '',
			'arh' => '',	'arhk' => '',	'arhe' => 0,	'arhs' => 0,	'arhsk' => '',
			'arf' => '',	'arfk' => '',	'arfe' => 0,	'arfs' => 0,	'arfsk' => '',
			'ara' => '',	'arak' => '',	'arae' => 0,	'aras' => 0,	'arask' => '',
			'art' => '',	'artk' => '',	'arte' => 0,	'arts' => 0,	'artsk' => '',
			'itm0' => '',	'itmk0' => '',	'itme0' => 0,	'itms0' => 0,	'itmsk0' => '',
			'itm1' => '',	'itmk1' => '',	'itme1' => 0,	'itms1' => 0,	'itmsk1' => '',
			'itm2' => '',	'itmk2' => '',	'itme2' => 0,	'itms2' => 0,	'itmsk2' => '',
			'itm3' => '',	'itmk3' => '',	'itme3' => 0,	'itms3' => 0,	'itmsk3' => '',
			'itm4' => '',	'itmk4' => '',	'itme4' => 0,	'itms4' => 0,	'itmsk4' => '',
			'itm5' => '',	'itmk5' => '',	'itme5' => 0,	'itms5' => 0,	'itmsk5' => '',
			'itm6' => '',	'itmk6' => '',	'itme6' => 0,	'itms6' => 0,	'itmsk6' => '',
		);
	$anpcinfo = array
		( 
		4 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 33,
			'mhp' => 300,
			'msp' => 400,
			'att' => 800000,
			'def' => 800000,
			'lvl' => 250,
			'skill' => 50000,
			'money' => 1,
			'arb' => '黑色连衣裙',
			'arbk' => 'DB',
			'arbe' => 800,
			'arbs' => 20,
			'arbsk' => 'Aa',
			'arh' => '红色的丝带',
			'arhk' => 'DH',
			'arhe' => 800,
			'arhs' => 15,
			'arhsk' => 'B',
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 800,
			'arfs' => 21,
			'ara' => '红色的丝带',
			'arak' => 'DA',
			'arae' => 800,
			'aras' => 15,
			'arask' => 'b',
			'art' => '红黑色的耳塞',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'W',
			'sub' => array
			(
				0 => array
				(
				'name' => '■',
				'icon' => 83,
				'wep' => '红色的丝带',
				'wepk' => 'WP',
				'wepe' => 800,
				'weps' => 20,
				'wepsk' => 'uy',
				'itm1' => '十字发卡',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				'description' => '拟似意识 ■ (通称篝)。如果仓促上阵，<span class="yellow b">不仅难以击倒她，而且很容易屈死于她之手！</span>',
				),
			),
		),
		7 => array
			(
			'mode' => 1,
			'num' => 3,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'rage' => 100,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'pls' => 99,
			'mhp' => 2550,
			'msp' => 400,
			'att' => 250,
			'def' => 750,
			'lvl' => 60,
			'skill' => 500,
			'money' => 24000,
			'arb' => '【执行官装甲-改】',
			'arbk' => 'DB',
			'arbe' => 700,
			'arbs' => 120,
			'arbsk' => 'Aa',
			'arh' => '【执行官头盔-改】',
			'arhk' => 'DH',
			'arhe' => 500,
			'arhs' => 120,
			'arhsk' => '',
			'arf' => '【执行官战靴-改】',
			'arfk' => 'DF',
			'arfe' => 480,
			'arfs' => 120,
			'arfsk' => '',
			'ara' => '【执行官护手-改】',
			'arak' => 'DA',
			'arae' => 480,
			'aras' => 120,
			'arask' => 'c',
			'art' => '【HP制御系统】',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
	//		'itm5' => '好人卡',
	//		'itmk5' => 'Y',
	//		'itme5' => 1,
	//		'itms5' => 240,
			'sub' => array
			(
				0 => array
				(
				'name' => '电击使 御坂 美琴',
				'icon' => 41,
				'gd' => 'f',
				'wep' => '【科学的超电磁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'ed',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				1 => array
				(
				'name' => '班主任 坂持 金发',
				'icon' => 42,
				'gd' => 'm',
				'wep' => '【水素粒子水铁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'id',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				2 => array
				(
				'name' => '花之领主 风见 幽香',
				'icon' => 43,
				'gd' => 'f',
				'wep' => '魔炮【元祖二重魔炮】',
				'wepk' => 'WF',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'pd',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
		
		12 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'skills' => array('401'=>'5'),
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 1800,
			'msp' => 400,
			'att' => 150,
			'def' => 260,
			'lvl' => 18,
			'skill' => 30,
			'money' => 1,
			'arb' => '黑色哥特装',
			'arbk' => 'DB',
			'arbe' => 25,
			'arbs' => 20,
			'arh' => '不明饰物',
			'arhk' => 'DH',
			'arhe' => 12,
			'arhs' => 15,
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 18,
			'arfs' => 21,
			'ara' => '黑铁镣铐',
			'arak' => 'DA',
			'arae' => 5,
			'aras' => 15,
			'art' => '镣铐的碎片',
			'artk' => 'Y',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => 'Dark Force幼体',
				'icon' => 81,
				'wep' => 'RV『Black Riper』',
				'wepk' => 'WG',
				'wepe' => 80,
				'weps' => 125,
				'wepsk' => 'c',
				),
			),
		),
		
		13 => array(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 5,
			'pose'=> 0,
			'tactic' => 0,
			'killnum' => 0,
			'teamID' => '循环',
			'teampsss' => 'circle',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 600,
			'msp' => 400,
			'att' => 150,
			'def' => 100,
			'lvl' => 10,
			'skill' => 50,
			'money' => 500,
			'arb' => '旧式布拉吉',
			'arbk' => 'DB',
			'arbe' => 75,
			'arbs' => 20,
			'arbsk' => '',
			'arh' => '蝙蝠羽翼帽子',
			'arhk' => 'DH',
			'arhe' => 75,
			'arhs' => 20,
			'arf' => '女式皮鞋',
			'arfk' => 'DF',
			'arfe' => 75,
			'arfs' => 20,
			'ara' => '粉色披风',
			'arak' => 'DA',
			'arae' => 50,
			'aras' => 25,
			'art' => '飞行之愿',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
			'sub' => array
			(
				0 => array
				(
				'name' => '库特',
				'icon' => 8,
				'wep' => '光束镰刀',
				'wepk' => 'WK',
				'wepe' => 100,
				'weps' => 36,
				'wepsk' => 'ec',
				),
			),
		), 
		42 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 17,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'f',
			'pls' => 34,
			'mhp' => 37000000,
			'msp' => 8000,
			'att' => 115,
			'def' => 115,
			'lvl' => 115,
			'skill' => 666,
			'skills' => array('21'=>'0','81'=>'0', '432'=>'0', '461'=>'1', '508'=>'0', '509'=>'0'),
			'money' => 115,
			'arb' => '直播长睡袍「Kipli」',
			'arbk' => 'DB',
			'arbe' => 1690000,
			'arbs' => 900,
			'arbsk' => 'Bh',
			'arh' => '橘色虎纹猫「15」',
			'arhk' => 'DH',
			'arhe' => 1440000,
			'arhs' => 900,
			'arhsk' => 'Lny',
			'ara' => '危险塑料袋「Nata」',
			'arak' => 'DA',
			'arae' => 1440000,
			'aras' => 900,
			'arask' => 'Ha',
			'arf' => '邋遢棉毛袜「Aich」',
			'arfk' => 'DF',
			'arfe' => 1440000,
			'arfs' => 900,
			'arfsk' => 'AM',
			'art' => 'V.H.虚拟娱乐主义',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'Vtb',
			'sub' => array
			(
				0 => array
				(
				'name' => '一一五',
				'icon' => 'avatar_rek/115_s.png',
				'wep' => '黄金·沙漠之鹰',
				'wepk' => 'WG',
				'wepe' => 20000,
				'weps' => 9999,
				'wepsk' => 'wNy',
				'itm1' => '开心的刀',
				'itmk1' => 'WK',
				'itme1' => 32767,
				'itms1' => 9999,
				'itmsk1' => 'crfN',
				'itm2' => '发条式突击步枪 AR-47',
				'itmk2' => 'WG',
				'itme2' => 18000,
				'itms2' => 9999,
				'itmsk2' => 'rnN',
				'itm3' => '神圣手榴弹',
				'itmk3' => 'WC',
				'itme3' => 32000,
				'itms3' => 9999,
				'itmsk3' => 'dkN',
				'description' => '断罪女神 一一五，身上的装备其实是权限套装<s style="color:#333">外挂</s>。其极端突出的攻防让她本身的操作变得无关紧要了。',
				),
			),
		),
		46 => array
		(
			'mode' => 2,
			'num' => 1,
			'pass' => 'bra',
			'club' => 17,
			'bid' => 0,
			'inf' => '',
			'rage' => 15,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampass' => '',
			'pls' => 99,
			'mhp' => 4400,
			'msp' => 1000,
			'att' => 300,
			'def' => 500,
			'lvl' => 40,
			'skill' => 333,
			'money' => 20,
			'arb' => '全息实体战装',
			'arbk' => 'DB',
			'arbe' => 1200,
			'arbs' => 30,
			'arbsk' => 'A',
			'arh' => '全息实体战盔',
			'arhk' => 'DH',
			'arhe' => 1200,
			'arhs' => 30,
			'arhsk' => 'a',
			'ara' => '全息实体战盾',
			'arak' => 'DA',
			'arae' => 1200,
			'aras' => 30,
			'arask' => 'R',
			'arf' => '全息实体战靴',
			'arfk' => 'DF',
			'arfe' => 1200,
			'arfs' => 30,
			'arfsk' => 'M',
			'art' => '全息实体的自律回路',
			'artk' => 'A',
			'arte' => 1200,
			'arts' => 30,
			'artsk' => 'cH',
			'sub' => array
			(
				0 => array
				 (
				'name' => '熵魔法传人 Howling',
				'icon' => 'avatar_kh/howling.jpg',
				'gd' => 'f',
				'mss' => 50,
				'skills' => array('404'=>'3','461'=>'1','486'=>'2'),
				'wep' => '烈爪拳 Huitzil',
				'wepk' => 'WP',
				'wepe' => 360,
				'weps' => 600,
				'wepsk' => 'ufr',
				'arb' => '蓬松运动连衣裙',
				'arh' => '异域风情的围巾',
				'ara' => '附魔之神爪 Ketsal',
				'arask' => 'NR',
				'arf' => '前端开口的长筒靴',
				'itm1' => '★长着兽耳的卡牌包★',
				'itmk1' => 'VO4',
				'itme1' => 1,
				'itms1' => 1,
				'itmsk1' => '201',
				'description' => '全息实体 熵魔法传人 Howling，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是残血时概率复活',
				),
			1 => array
				(
				'name' => '幻影斗将神 S.A.S',
				'icon' => 'avatar_kh/SAS.jpg',
				'gd' => 'f',
				'mss' => 50,
				'skills' => array('404'=>'3','461'=>'1','485'=>'2'),
				'wep' => '断天镰·碎星',
				'wepk' => 'WK',
				'wepe' => 360,
				'weps' => 600,
				'wepsk' => 'rnc',
				'arb' => '圣战士之甲',
				'arh' => '圣战士之盔',
				'ara' => '圣战士之盾',
				'arf' => '圣战士之靴',
				'itm1' => '★锋利的卡牌包★',
				'itmk1' => 'VO4',
				'itme1' => 1,
				'itms1' => 1,
				'itmsk1' => '200',
				'description' => '全息实体 幻影斗将神 S.A.S，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是对杀人数越多的对手造成的伤害越大',
				),
			2 => array
				(
				'name' => '银白愿天使 Annabelle',
				'icon' => 'avatar_kh/annabelle.jpg',
				'gd' => 'f',
				'mss' => 50,
				'skills' => array('404'=>'3','461'=>'1','489'=>'0'),
				'wep' => '『亚兹拉尔的死亡之叶』',
				'wepk' => 'WC',
				'wepe' => 360,
				'weps' => 600,
				'wepsk' => 'Lir',
				'arb' => '密涅瓦之衣',
				'arh' => '梅塔伊恩之冠',
				'ara' => '朱庇特之巾',
				'arf' => '堕天使之羽翼',
				'arfsk' => 'Mm',
				'itm1' => '★羽翼卡牌包★',
				'itmk1' => 'VO4',
				'itme1' => 1,
				'itms1' => 1,
				'itmsk1' => '203',
				'description' => '全息实体 银白愿天使 Annabelle，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是会将所受的异常状态反弹给对手。',
				),
			3 => array
				(
				'name' => '通灵冒险家 星海',
				'icon' => 'avatar_kh/xinghai.jpg',
				'gd' => 'f',
				'mss' => 50,
				'skills' => array('404'=>'3','461'=>'1','488'=>'0'),
				'wep' => '泰瑟远距电击枪',
				'wepk' => 'WG',
				'wepe' => 360,
				'weps' => 600,
				'wepsk' => 'Ser',
				'arb' => '内插钢板的西装',
				'arh' => '水晶灵视眼镜',
				'ara' => '内藏机关的手套',
				'arf' => '耐磨的灰色长裤',
				'arfs' => 200,
				'itm1' => '★套了好几层的卡牌包★',
				'itmk1' => 'VO4',
				'itme1' => 1,
				'itms1' => 1,
				'itmsk1' => '202',
				'description' => '全息实体 通灵冒险家 星海，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是HP低于一半后会回复受到攻击一半的生命值',
				),
			4 => array
				(
				'name' => '麻烦妖精 Sophia',
				'icon' => 'avatar_kh/sophia.jpg',
				'gd' => 'f',
				'mss' => 50,
				'skills' => array('404'=>'3','461'=>'1','491'=>'0'),
				'wep' => '空想波动 ~ 共鸣冲击',
				'wepk' => 'WD',
				'wepe' => 360,
				'weps' => 600,
				'wepsk' => 'rwd',
				'arb' => '空想模样的裙子',
				'arh' => '空想模样的头饰',
				'ara' => '空想模样的手套',
				'arf' => '空想模样的靴子',
				'itm1' => '★蠢萌的卡牌包★',
				'itmk1' => 'VO4',
				'itme1' => 1,
				'itms1' => 1,
				'itmsk1' => '204',
				'description' => '全息实体 麻烦妖精 Sophia，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是随机强化武器效果。',
				),
			),
		),
	);

	//campfireMOD新增addnpc
	$anpcinfo[1001]=array
	(
		'mode' => 1,
		'num' => 1,
		'pass' => 'bra',
		'bid' => 0,
		'inf' => '',
		'state' => 1,
		'rage' => 30,
		'pose'=> 2,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teampsss' => '',
		'gd' => 'r',
		'pls' => 99,
		'mhp' => 7800,
		'msp' => 7800,
		'att' => 1700,
		'def' => 1300,
		'lvl' => 65,
		'skill' => 599,
		'skills' => array('403'=>'1'),
		'money' => 4500,
		'arb' => '资讯装甲-B',
		'arbk' => 'DBPC',
		'arbe' => 3400,
		'arbs' => 1400,
		'arbsk' => 'ab',
		'arh' => '资讯装甲-H',
		'arhk' => 'DHPC',
		'arhe' => 1600,
		'arhs' => 1200,
		'arhsk' => 'H',
		'ara' => '资讯装甲-A',
		'arak' => 'DAPC',
		'arae' => 1300,
		'aras' => 1300,
		'arask' => 'Ac',
		'arf' => '资讯装甲-F',
		'arfk' => 'DFPC',
		'arfe' => 1300,
		'arfs' => 1200,
		'arfsk' => 'Mm',
		'art' => 'CORE:0x4B',
		'artk' => 'A',
		'arte' => 1,
		'arts' => 1,
		'itm1' => '阿波罗之匣',
		'itmk1' => 'kggb',
		'itme1' => 1,
		'itms1' => 3,
		'itm2' => '自适应型溶剂TA-E3',
		'itmk2' => 'MH',
		'itme2' => 20,
		'itms2' => 1,
		'itm3' => '高密度压缩干粮',
		'itmk3' => 'HB',
		'itme3' => 1500,
		'itms3' => 150,
		'description' => '虚拟体-C型，身穿动力装甲的虚拟结构体，<span class="yellow b">基本可以看作是给玩家送钱以及磨刀的高级兵。</span><br>“看上去有几千耐久，实际上一发就打没了。”——不愿透露姓名的小五。',
		'sub' => array
		(
			0 => array
			(
			'name' => '0x47554E_G',
			'icon' => 10011,
			'club' => 3,
			'wep' => '高能粒子束发射装置',
			'wepk' => 'WG',
			'wepe' => 2800,
			'weps' => 1200,
			'wepsk' => 'Bnfd',
			),
			1 => array
			(
			'name' => '0x4B4E46_K',
			'icon' => 10012,
			'club' => 2,
			'wep' => '高周波切割装置',
			'wepk' => 'WK',
			'wepe' => 1400,
			'weps' => 1200,
			'wepsk' => 'Bnrk',
			),
			2 => array
			(
			'name' => '0x505753_P',
			'icon' => 10013,
			'club' => 1,
			'wep' => '高频动力装甲拳套',
			'wepk' => 'WP',
			'wepe' => 2300,
			'weps' => 1200,
			'wepsk' => 'BNnr',
			),
		),
	);
	$anpcinfo[1002]=array
	(
		'mode' => 1,
		'num' => 1,
		'pass' => 'bra',
		'bid' => 0,
		'inf' => '',
		'state' => 1,
		'rage' => 50,
		'pose'=> 2,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teampsss' => '',
		'gd' => 'r',
		'pls' => 99,
		'mhp' => 9200,
		'msp' => 9200,
		'att' => 2000,
		'def' => 1500,
		'lvl' => 78,
		'skill' => 599,
		'skills' => array('403'=>'1','461'=>'1','432'=>'0'),
		'money' => 0,
		'arb' => '拟似装甲-B',
		'arbk' => 'DBPB',
		'arbe' => 6200,
		'arbs' => 3000,
		'arbsk' => 'ab',
		'arh' => '拟似装甲-H',
		'arhk' => 'DHPB',
		'arhe' => 2100,
		'arhs' => 3500,
		'arhsk' => 'HB',
		'ara' => '拟似装甲-A',
		'arak' => 'DAPB',
		'arae' => 1700,
		'aras' => 3500,
		'arask' => 'Ac',
		'arf' => '拟似装甲-F',
		'arfk' => 'DFPB',
		'arfe' => 1700,
		'arfs' => 3500,
		'arfsk' => 'Mm',
		'art' => '拟似核心:0x4C',
		'artk' => 'A',
		'arte' => 1,
		'arts' => 1,
		'artsk' => 'hL',
		'itm1' => '阿斯忒瑞亚之匣',
		'itmk1' => 'kgpb',
		'itme1' => 1,
		'itms1' => 1,
		'itm2' => '自适应型溶剂TA-E3',
		'itmk2' => 'MH',
		'itme2' => 20,
		'itms2' => 4,
		'sub' => array
		(
			0 => array
			(
			'name' => 'VIA-61-AETHER',
			'icon' => 10021,
			'club' => 3,
			'wep' => '棘枪',
			'wepk' => 'WJ',
			'wepe' => 1800,
			'weps' => 1500,
			'wepsk' => 'nN',
			'itm3' => '光辉',
			'itmk3' => 'X',
			'itme3' => 1,
			'itms3' => 1,
			'itmsk3' => 'x',
			'description' => '虚拟体-V型 VIA-61-AETHER，<span class="yellow b">手持重型枪械的虚拟体，其攻击能穿透对手的物理防御。</span><br>是V-61型虚拟体的「复写」版本。',
			),
			1 => array
			(
			'name' => 'VIA-61',
			'icon' => 10022,
			'club' => 3,
			'wep' => '厄环',
			'wepk' => 'WJ',
			'wepe' => 2200,
			'weps' => 1500,
			'wepsk' => 'ykd',
			'itm3' => '荣耀',
			'itmk3' => 'X',
			'itme3' => 1,
			'itms3' => 1,
			'itmsk3' => 'x',
			'description' => '虚拟体-V型 VIA-61，<span class="yellow b">手持重型枪械的虚拟体，其攻击能穿透对手的属性防御。</span><br>V-61型虚拟体的形象来自于小说《偶像信仰》中的人气配角安可，在小说中，她是主角堇川苹最早遇到的科技势力成员。',
			),
			2 => array
			(
			'name' => 'VIA-54-AETHER',
			'icon' => 10023,
			'club' => 9,
			'wep' => '黄昏',
			'wepk' => 'WF',
			'wepe' => 800,
			'weps' => '∞',
			'wepsk' => 'nrN',
			'itm3' => '奉献',
			'itmk3' => 'X',
			'itme3' => 1,
			'itms3' => 1,
			'itmsk3' => 'x',
			'description' => '虚拟体-V型 VIA-54-AETHER，<span class="yellow b">手持黑色灵书的虚拟体，其攻击能穿透对手的物理防御。</span><br>是V-54型虚拟体的「复写」版本。',
			),
			3 => array
			(
			'name' => 'VIA-54',
			'icon' => 10024,
			'club' => 9,
			'wep' => '余晖',
			'wepk' => 'WF',
			'wepe' => 2500,
			'weps' => '∞',
			'wepsk' => 'ydf',
			'itm3' => '虔诚',
			'itmk3' => 'X',
			'itme3' => 1,
			'itms3' => 1,
			'itmsk3' => 'x',
			'description' => '虚拟体-V型 VIA-54，<span class="yellow b">手持黑色灵书的虚拟体，其攻击能穿透对手的属性防御。</span><br>V-54型虚拟体的形象来自于小说《偶像信仰》中的人气配角艾茜·弗洛格，在小说的前中期，她多以反派的形象出现，并因此收获了大量的人气，是主角堇川苹最早遇到的灵异势力成员。',
			),
		),
	);
	$anpcinfo[1003]=array
	(
		'mode' => 1,
		'num' => 1,
		'pass' => 'bra',
		'bid' => 0,
		'inf' => '',
		'state' => 1,
		'rage' => 100,
		'pose'=> 2,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teampsss' => '',
		'gd' => 'r',
		'pls' => 0,
		'mhp' => 2250,
		'msp' => 1175,
		'att' => 400,
		'def' => 250,
		'lvl' => 112,
		'skill' => 129,
		'skills' => array('403'=>'4'),
		'money' => 0,
		'arb' => '未测试动力装甲-B',
		'arbk' => 'DBPS',
		'arbe' => 7200,
		'arbs' => 2400,
		'arbsk' => 'Bh',
		'arh' => '未测试动力装甲-H',
		'arhk' => 'DHPS',
		'arhe' => 3200,
		'arhs' => 1600,
		'arhsk' => 'b',
		'ara' => '未测试动力装甲-A',
		'arak' => 'DAPS',
		'arae' => 3200,
		'aras' => 1600,
		'arask' => 'H',
		'arf' => '未测试动力装甲-F',
		'arfk' => 'DFPS',
		'arfe' => 3200,
		'arfs' => 1600,
		'arfsk' => 'm',
		'art' => '造型奇特的终端机',
		'artk' => 'A',
		'arte' => 1,
		'arts' => 1,
		'artsk' => 'x',
		'sub' => array
		(
			0 => array
			(
			'name' => 'Mr.Lein',
			'icon' => 0,
			'club' => 7,
			'wep' => '燃素粒子炮-高出力属性解放型',
			'wepk' => 'WJ',
			'wepe' => 3800,
			'weps' => 1500,
			'wepsk' => 'Nnufd',
			),
		),
	);
	$anpcinfo[1004]=array
	(
		'mode' => 1,
		'num' => 4,
		'pass' => 'bra',
		'bid' => 0,
		'inf' => '',
		'state' => 1,
		'rage' => 0,
		'pose'=> 2,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teampsss' => '',
		'gd' => 'r',
		'pls' => 0,
		'mhp' => 1750,
		'msp' => 1,
		'att' => 1500,
		'def' => 1500,
		'lvl' => 98,
		'skill' => 599,
		'skills' => array('403'=>'2'),
		'money' => 0,
		'arb' => '制式动力装甲-B',
		'arbk' => 'DBPB',
		'arbe' => 2400,
		'arbs' => 1200,
		'arbsk' => 'B',
		'arh' => '制式动力装甲-H',
		'arhk' => 'DHPB',
		'arhe' => 2400,
		'arhs' => 1200,
		'arhsk' => 'h',
		'ara' => '制式动力装甲-A',
		'arak' => 'DAPB',
		'arae' => 2400,
		'aras' => 1200,
		'arask' => 'b',
		'arf' => '制式动力装甲-F',
		'arfk' => 'DFPB',
		'arfe' => 2400,
		'arfs' => 1200,
		'arfsk' => 'Aa',
		'art' => 'CORE:0x4E',
		'artk' => 'A',
		'arte' => 1,
		'arts' => 1,
		'sub' => array
		(
			0 => array
			(
			'name' => '第三部门序列E-1',
			'icon' => 0,
			'club' => 7,
			'wep' => '防风武装',
			'wepk' => 'WJ',
			'wepe' => 2600,
			'weps' => 1500,
			'wepsk' => 'Nnufd',
			),
			1 => array
			(
			'name' => '第三部门序列E-3',
			'icon' => 0,
			'club' => 7,
			'wep' => '防风武装',
			'wepk' => 'WJ',
			'wepe' => 2600,
			'weps' => 1500,
			'wepsk' => 'Nnufd',
			),
			2 => array
			(
			'name' => '第三部门序列E-D',
			'icon' => 0,
			'club' => 7,
			'wep' => '防风武装',
			'wepk' => 'WJ',
			'wepe' => 2600,
			'weps' => 1500,
			'wepsk' => 'Nnufd',
			),
			3 => array
			(
			'name' => '第三部门序列E-0',
			'icon' => 0,
			'club' => 7,
			'wep' => '防风武装',
			'wepk' => 'WJ',
			'wepe' => 2600,
			'weps' => 1500,
			'wepsk' => 'Nnufd',
			),
		),
	);
}

?>