<?php

namespace addnpc
{
	$npcinit = array
		(
			'name' => '',	'pass' => 'bra', 'gd' => 'm',	'icon' => 0,	'club' => 0,	
			'mhp' => 0,	'msp' => 0,	'att' => 0,	'def' => 0,	'pls' => 0,	'lvl' => 0,
			'money' => 0,	'inf' => '',	'rage' => 0,	'pose' => 0,	'tactic' => 0,	
			'killnum' => 0,	'state' => 1,	'teamID' => '',	'teamPass' => '','bid' => 0,
			'wep' => '',	'wepk' => '',	'wepe' => 0,	'weps' => 0,	'wepsk' => '',
			'arb' => '',	'arbk' => '',	'arbe' => 0,	'arbs' => 0,	'arbsk' => '',
			'arh' => '',	'arhk' => '',	'arhe' => 0,	'arhs' => 0,	'arhsk' => '',
			'arf' => '',	'arfk' => '',	'arfe' => 0,	'arfs' => 0,	'arfsk' => '',
			'ara' => '',	'arak' => '',	'arae' => 0,	'aras' => 0,	'arask' => '',
			'art' => '',	'artk' => '',	'arte' => 0,	'arts' => 0,	'artsk' => '',
			'itm0' => '',	'itmk0' => '',	'itme0' => 0,	'itms0' => 0,	'itmsk0' => '',
			'itm1' => '',	'itmk1' => '',	'itme1' => 0,	'itms1' => 0,	'itmsk1' => '',
			'itm2' => '',	'itmk2' => '',	'itme2' => 0,	'itms2' => 0,	'itmsk2' => '',
			'itm3' => '',	'itmk3' => '',	'itme3' => 0,	'itms3' => 0,	'itmsk3' => '',
			'itm4' => '',	'itmk4' => '',	'itme4' => 0,	'itms4' => 0,	'itmsk4' => '',
			'itm5' => '',	'itmk5' => '',	'itme5' => 0,	'itms5' => 0,	'itmsk5' => '',
			'itm6' => '',	'itmk6' => '',	'itme6' => 0,	'itms6' => 0,	'itmsk6' => '',
		);
	$anpcinfo = array
		( 
		4 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 33,
			'mhp' => 300,
			'msp' => 400,
			'att' => 800000,
			'def' => 800000,
			'lvl' => 250,
			'skill' => 50000,
			'money' => 1,
			'arb' => '黑色连衣裙',
			'arbk' => 'DB',
			'arbe' => 800,
			'arbs' => 20,
			'arbsk' => 'Aa',
			'arh' => '红色的丝带',
			'arhk' => 'DH',
			'arhe' => 800,
			'arhs' => 15,
			'arhsk' => 'B',
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 800,
			'arfs' => 21,
			'ara' => '红色的丝带',
			'arak' => 'DA',
			'arae' => 800,
			'aras' => 15,
			'arask' => 'b',
			'art' => '红黑色的耳塞',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'W',
			'sub' => array
			(
				0 => array
				(
				'name' => '■',
				'icon' => 83,
				'wep' => '红色的丝带',
				'wepk' => 'WP',
				'wepe' => 800,
				'weps' => 20,
				'wepsk' => 'uy',
				'itm1' => '十字发卡',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				'description' => '拟似意识 ■ (通称篝)。如果仓促上阵，<span class="yellow">不仅难以击倒她，而且很容易屈死于她之手！</span>',
				),
			),
		),
		7 => array
			(
			'mode' => 1,
			'num' => 3,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'rage' => 100,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'pls' => 99,
			'mhp' => 2550,
			'msp' => 400,
			'att' => 250,
			'def' => 750,
			'lvl' => 60,
			'skill' => 500,
			'money' => 24000,
			'arb' => '【执行官装甲-改】',
			'arbk' => 'DB',
			'arbe' => 700,
			'arbs' => 120,
			'arbsk' => 'Aa',
			'arh' => '【执行官头盔-改】',
			'arhk' => 'DH',
			'arhe' => 500,
			'arhs' => 120,
			'arhsk' => '',
			'arf' => '【执行官战靴-改】',
			'arfk' => 'DF',
			'arfe' => 480,
			'arfs' => 120,
			'arfsk' => '',
			'ara' => '【执行官护手-改】',
			'arak' => 'DA',
			'arae' => 480,
			'aras' => 120,
			'arask' => 'c',
			'art' => '【HP制御系统】',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
	//		'itm5' => '好人卡',
	//		'itmk5' => 'Y',
	//		'itme5' => 1,
	//		'itms5' => 240,
			'sub' => array
			(
				0 => array
				(
				'name' => '电击使 御坂 美琴',
				'icon' => 41,
				'gd' => 'f',
				'pls' => 17,
				'wep' => '【科学的超电磁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'ed',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				1 => array
				(
				'name' => '班主任 坂持 金发',
				'icon' => 42,
				'gd' => 'm',
				'pls' => 5,
				'wep' => '【水素粒子水铁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'id',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				2 => array
				(
				'name' => '花之领主 风见 幽香',
				'icon' => 43,
				'gd' => 'f',
				'pls' => 6,
				'wep' => '魔炮【元祖二重魔炮】',
				'wepk' => 'WF',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'pd',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
		
		12 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'skills' => array('401'=>'5'),
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 1800,
			'msp' => 400,
			'att' => 150,
			'def' => 260,
			'lvl' => 18,
			'skill' => 30,
			'money' => 1,
			'arb' => '黑色哥特装',
			'arbk' => 'DB',
			'arbe' => 25,
			'arbs' => 20,
			'arh' => '不明饰物',
			'arhk' => 'DH',
			'arhe' => 12,
			'arhs' => 15,
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 18,
			'arfs' => 21,
			'ara' => '黑铁镣铐',
			'arak' => 'DA',
			'arae' => 5,
			'aras' => 15,
			'art' => '镣铐的碎片',
			'artk' => 'Y',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => 'Dark Force幼体',
				'icon' => 81,
				'wep' => 'RV『Black Riper』',
				'wepk' => 'WG',
				'wepe' => 80,
				'weps' => 125,
				'wepsk' => 'c',
				),
			),
		),
		
		13 => array(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 5,
			'pose'=> 0,
			'tactic' => 0,
			'killnum' => 0,
			'teamID' => '循环',
			'teampsss' => 'circle',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 600,
			'msp' => 400,
			'att' => 150,
			'def' => 100,
			'lvl' => 10,
			'skill' => 50,
			'money' => 500,
			'arb' => '旧式布拉吉',
			'arbk' => 'DB',
			'arbe' => 75,
			'arbs' => 20,
			'arbsk' => '',
			'arh' => '蝙蝠羽翼帽子',
			'arhk' => 'DH',
			'arhe' => 75,
			'arhs' => 20,
			'arf' => '女式皮鞋',
			'arfk' => 'DF',
			'arfe' => 75,
			'arfs' => 20,
			'ara' => '粉色披风',
			'arak' => 'DA',
			'arae' => 50,
			'aras' => 25,
			'art' => '飞行之愿',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
			'sub' => array
			(
				0 => array
				(
				'name' => '库特',
				'icon' => 8,
				'wep' => '光束镰刀',
				'wepk' => 'WK',
				'wepe' => 100,
				'weps' => 36,
				'wepsk' => 'ec',
				),
			),
		), 
		75 => array
			(
			'mode' => 1,
			'num' => 45,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 30,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'r',
			'pls' => 99,
			'mhp' => 7800,
			'msp' => 7800,
			'att' => 1700,
			'def' => 1300,
			'lvl' => 65,
			'skill' => 599,
			'skills' => array('403'=>'1'),
			'money' => 0,
			'arb' => '资讯装甲-B',
			'arbk' => 'DB',
			'arbe' => 3400,
			'arbs' => 1400,
			'arbsk' => 'ab',
			'arh' => '资讯装甲-H',
			'arhk' => 'DH',
			'arhe' => 1600,
			'arhs' => 1200,
			'arhsk' => 'H',
			'ara' => '资讯装甲-A',
			'arak' => 'DA',
			'arae' => 1300,
			'aras' => 1300,
			'arask' => 'Ac',
			'arf' => '资讯装甲-F',
			'arfk' => 'DF',
			'arfe' => 1300,
			'arfs' => 1200,
			'arfsk' => 'Mm',
			'art' => 'CORE:0x4B',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => '0x47554E',
				'icon' => 0,
				'club' => 3,
				'wep' => '高能粒子束发射装置',
				'wepk' => 'WG',
				'wepe' => 2800,
				'weps' => 1200,
				'wepsk' => 'nfd',
				),
				1 => array
				(
				'name' => '0x4B4E46',
				'icon' => 0,
				'club' => 2,
				'wep' => '高周波切割装置',
				'wepk' => 'WK',
				'wepe' => 1400,
				'weps' => 1200,
				'wepsk' => 'nrk',
				),
				2 => array
				(
				'name' => '0x505753',
				'icon' => 0,
				'club' => 1,
				'wep' => '高频动力装甲拳套',
				'wepk' => 'WP',
				'wepe' => 2300,
				'weps' => 1200,
				'wepsk' => 'Nnr',
				),
			),
		),
		76 => array
			(
			'mode' => 1,
			'num' => 12,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 50,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'r',
			'pls' => 99,
			'mhp' => 9200,
			'msp' => 9200,
			'att' => 2000,
			'def' => 1500,
			'lvl' => 78,
			'skill' => 599,
			'skills' => array('403'=>'2'),
			'money' => 0,
			'arb' => '复写装甲-B',
			'arbk' => 'DB',
			'arbe' => 6200,
			'arbs' => 1400,
			'arbsk' => 'ab',
			'arh' => '复写装甲-H',
			'arhk' => 'DH',
			'arhe' => 2100,
			'arhs' => 1200,
			'arhsk' => 'H',
			'ara' => '复写装甲-A',
			'arak' => 'DA',
			'arae' => 1700,
			'aras' => 1300,
			'arask' => 'Ac',
			'arf' => '复写装甲-F',
			'arfk' => 'DF',
			'arfe' => 1700,
			'arfs' => 1200,
			'arfsk' => 'Mm',
			'art' => 'CORE:0x4C',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => '0xEA61',
				'icon' => 0,
				'club' => 3,
				'wep' => '夜母',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'nck',
				),
				1 => array
				(
				'name' => '0xEA62',
				'icon' => 0,
				'club' => 4,
				'wep' => '棘枪',
				'wepk' => 'WC',
				'wepe' => 3500,
				'weps' => 2300,
				'wepsk' => 'Nnfk',
				),
				2 => array
				(
				'name' => '0xEA63',
				'icon' => 0,
				'club' => 5,
				'wep' => '厄环',
				'wepk' => 'WD',
				'wepe' => 2800,
				'weps' => 2300,
				'wepsk' => 'nd',
				),
				3 => array
				(
				'name' => '0xEA64',
				'icon' => 0,
				'club' => 9,
				'wep' => '上灵',
				'wepk' => 'WF',
				'wepe' => 700,
				'weps' => 1500,
				'wepsk' => 'nr',
				),
			),
		),
		78 => array
			(
			'mode' => 1,
			'num' => 4,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 0,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'r',
			'pls' => 0,
			'mhp' => 1750,
			'msp' => 1,
			'att' => 1500,
			'def' => 1500,
			'lvl' => 98,
			'skill' => 599,
			'skills' => array('403'=>'2'),
			'money' => 0,
			'arb' => '制式动力装甲-B',
			'arbk' => 'DB',
			'arbe' => 2400,
			'arbs' => 1200,
			'arbsk' => 'BY',
			'arh' => '制式动力装甲-H',
			'arhk' => 'DH',
			'arhe' => 2400,
			'arhs' => 1200,
			'arhsk' => 'hY',
			'ara' => '制式动力装甲-A',
			'arak' => 'DA',
			'arae' => 2400,
			'aras' => 1200,
			'arask' => 'bY',
			'arf' => '制式动力装甲-F',
			'arfk' => 'DF',
			'arfe' => 2400,
			'arfs' => 1200,
			'arfsk' => 'AaY',
			'art' => 'CORE:0x4E',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => '序列E-1',
				'icon' => 0,
				'club' => 7,
				'wep' => '防风武装',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
				1 => array
				(
				'name' => '序列E-1',
				'icon' => 0,
				'club' => 7,
				'wep' => '防风武装',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
				2 => array
				(
				'name' => '序列E-1',
				'icon' => 0,
				'club' => 7,
				'wep' => '防风武装',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
				3 => array
				(
				'name' => '序列E-1',
				'icon' => 0,
				'club' => 7,
				'wep' => '防风武装',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
			),
		),
		77 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 100,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'r',
			'pls' => 0,
			'mhp' => 2250,
			'msp' => 1175,
			'att' => 400,
			'def' => 250,
			'lvl' => 112,
			'skill' => 799,
			'skills' => array('403'=>'4'),
			'money' => 0,
			'arb' => '未测试动力装甲-B',
			'arbk' => 'DB',
			'arbe' => 7200,
			'arbs' => 2400,
			'arbsk' => 'BhY',
			'arh' => '未测试动力装甲-H',
			'arhk' => 'DH',
			'arhe' => 3200,
			'arhs' => 1600,
			'arhsk' => 'bY',
			'ara' => '未测试动力装甲-A',
			'arak' => 'DA',
			'arae' => 3200,
			'aras' => 1600,
			'arask' => 'HY',
			'arf' => '未测试动力装甲-F',
			'arfk' => 'DF',
			'arfe' => 3200,
			'arfs' => 1600,
			'arfsk' => 'mY',
			'art' => 'Mr.Lein的终端机',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'x',
			'sub' => array
			(
				0 => array
				(
				'name' => 'Mr.Lein',
				'icon' => 0,
				'club' => 7,
				'wep' => '燃素粒子炮-蓄能型',
				'wepk' => 'WJ',
				'wepe' => 3800,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
			),
		),
		88 => array
			(
			'mode' => 1,
			'num' => 4,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'rage' => 188,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 88,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'm',
			'pls' => 99,
			'mhp' => 8888888,
			'msp' => 888,
			'att' => 88888,
			'def' => 88888,
			'lvl' => 88,
			'skill' => 88888,
			'money' => 88888,
			'arb' => '[数据删除]',
			'arbk' => 'DB',
			'arbe' => 8888,
			'arbs' => 8888,
			'arbsk' => 'Aa',
			'arh' => '[数据删除]',
			'arhk' => 'DH',
			'arhe' => 8888,
			'arhs' => 8888,
			'arhsk' => 'Bb',
			'arf' => '[数据删除]',
			'arfk' => 'DF',
			'arfe' => 8888,
			'arfs' => 8888,
			'arfsk' => 'Mm',
			'ara' => '[数据删除]',
			'arak' => 'DA',
			'arae' => 8888,
			'aras' => 8888,
			'arask' => 'Hc',
			'art' => '[数据删除]',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'xH',
			'sub' => array
			(
				0 => array
				(
				'name' => 'SCP-682',
				'icon' => 103,
				'wep' => '[数据删除]',
				'wepk' => 'WN',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				),
				1 => array
				(
				'name' => 'SCP-173',
				'icon' => 98,
				'wep' => '[数据删除]',
				'wepk' => 'WF',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				),
				2 => array
				(
				'name' => 'SCP-076',
				'icon' => 98,
				'wep' => '[数据删除]',
				'wepk' => 'WK',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				),
				3 => array
				(
				'name' => 'SCP-958',
				'icon' => 98,
				'wep' => '[数据删除]',
				'wepk' => 'WG',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				),
			),
		),
	);
}

?>