<?php

namespace addnpc
{
	$campfire_anpcinfo = array
		( 
		75 => array
			(
			'mode' => 1,
			'num' => 60,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 30,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'r',
			'pls' => 99,
			'mhp' => 7800,
			'msp' => 7800,
			'att' => 1700,
			'def' => 1300,
			'lvl' => 65,
			'skill' => 599,
			'skills' => array('403'=>'1'),
			'money' => 4500,
			'arb' => '资讯装甲-B',
			'arbk' => 'DBPB',
			'arbe' => 3400,
			'arbs' => 1400,
			'arbsk' => 'ab',
			'arh' => '资讯装甲-H',
			'arhk' => 'DHPB',
			'arhe' => 1600,
			'arhs' => 1200,
			'arhsk' => 'H',
			'ara' => '资讯装甲-A',
			'arak' => 'DAPB',
			'arae' => 1300,
			'aras' => 1300,
			'arask' => 'Ac',
			'arf' => '资讯装甲-F',
			'arfk' => 'DFPB',
			'arfe' => 1300,
			'arfs' => 1200,
			'arfsk' => 'Mm',
			'art' => 'CORE:0x4B',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'itm1' => '能量核心',
			'itmk1' => 'X',
			'itme1' => 1,
			'itms1' => 2,
			'itm2' => '自适应型溶剂TA-E3',
			'itmk2' => 'Y',
			'itme2' => 1,
			'itms2' => 1,
			'itm1' => '高密度压缩干粮',
			'itmk1' => 'HB',
			'itme1' => 1500,
			'itms1' => 150,
			'sub' => array
			(
				0 => array
				(
				'name' => '0x47554E',
				'icon' => 255,
				'club' => 3,
				'wep' => '高能粒子束发射装置',
				'wepk' => 'WG',
				'wepe' => 2800,
				'weps' => 1200,
				'wepsk' => 'Bnfd',
				),
				1 => array
				(
				'name' => '0x4B4E46',
				'icon' => 255,
				'club' => 2,
				'wep' => '高周波切割装置',
				'wepk' => 'WK',
				'wepe' => 1400,
				'weps' => 1200,
				'wepsk' => 'Bnrk',
				),
				2 => array
				(
				'name' => '0x505753',
				'icon' => 255,
				'club' => 1,
				'wep' => '高频动力装甲拳套',
				'wepk' => 'WP',
				'wepe' => 2300,
				'weps' => 1200,
				'wepsk' => 'BNnr',
				),
			),
		),
		76 => array
			(
			'mode' => 1,
			'num' => 12,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 50,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'r',
			'pls' => 99,
			'mhp' => 9200,
			'msp' => 9200,
			'att' => 2000,
			'def' => 1500,
			'lvl' => 78,
			'skill' => 599,
			'skills' => array('403'=>'2'),
			'money' => 0,
			'arb' => '复写装甲-B',
			'arbk' => 'DBPA',
			'arbe' => 6200,
			'arbs' => 1400,
			'arbsk' => 'ab',
			'arh' => '复写装甲-H',
			'arhk' => 'DHPA',
			'arhe' => 2100,
			'arhs' => 1200,
			'arhsk' => 'H',
			'ara' => '复写装甲-A',
			'arak' => 'DAPA',
			'arae' => 1700,
			'aras' => 1300,
			'arask' => 'Ac',
			'arf' => '复写装甲-F',
			'arfk' => 'DFPA',
			'arfe' => 1700,
			'arfs' => 1200,
			'arfsk' => 'Mm',
			'art' => 'CORE:0x4C',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => '0xEA61',
				'icon' => 0,
				'club' => 3,
				'wep' => '天基武器',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'nck',
				),
				1 => array
				(
				'name' => '0xEA62',
				'icon' => 0,
				'club' => 4,
				'wep' => '棘枪',
				'wepk' => 'WC',
				'wepe' => 3500,
				'weps' => 2300,
				'wepsk' => 'Nnfk',
				),
				2 => array
				(
				'name' => '0xEA63',
				'icon' => 0,
				'club' => 5,
				'wep' => '厄环',
				'wepk' => 'WD',
				'wepe' => 2800,
				'weps' => 2300,
				'wepsk' => 'nd',
				),
				3 => array
				(
				'name' => '0xEA64',
				'icon' => 0,
				'club' => 9,
				'wep' => '上灵',
				'wepk' => 'WF',
				'wepe' => 700,
				'weps' => 1500,
				'wepsk' => 'nr',
				),
			),
		),
		78 => array
			(
			'mode' => 1,
			'num' => 4,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 0,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'r',
			'pls' => 0,
			'mhp' => 1750,
			'msp' => 1,
			'att' => 1500,
			'def' => 1500,
			'lvl' => 98,
			'skill' => 599,
			'skills' => array('403'=>'2'),
			'money' => 0,
			'arb' => '制式动力装甲-B',
			'arbk' => 'DBPC',
			'arbe' => 2400,
			'arbs' => 1200,
			'arbsk' => 'BY',
			'arh' => '制式动力装甲-H',
			'arhk' => 'DHPC',
			'arhe' => 2400,
			'arhs' => 1200,
			'arhsk' => 'hY',
			'ara' => '制式动力装甲-A',
			'arak' => 'DAPC',
			'arae' => 2400,
			'aras' => 1200,
			'arask' => 'bY',
			'arf' => '制式动力装甲-F',
			'arfk' => 'DFPC',
			'arfe' => 2400,
			'arfs' => 1200,
			'arfsk' => 'AaY',
			'art' => 'CORE:0x4E',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => '第三部门序列E-1',
				'icon' => 0,
				'club' => 7,
				'wep' => '防风武装',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
				1 => array
				(
				'name' => '第三部门序列E-3',
				'icon' => 0,
				'club' => 7,
				'wep' => '防风武装',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
				2 => array
				(
				'name' => '第三部门序列E-D',
				'icon' => 0,
				'club' => 7,
				'wep' => '防风武装',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
				3 => array
				(
				'name' => '第三部门序列E-0',
				'icon' => 0,
				'club' => 7,
				'wep' => '防风武装',
				'wepk' => 'WJ',
				'wepe' => 2600,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
			),
		),
		77 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 100,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'r',
			'pls' => 0,
			'mhp' => 2250,
			'msp' => 1175,
			'att' => 400,
			'def' => 250,
			'lvl' => 112,
			'skill' => 129,
			'skills' => array('403'=>'4'),
			'money' => 0,
			'arb' => '未测试动力装甲-B',
			'arbk' => 'DBPT',
			'arbe' => 7200,
			'arbs' => 2400,
			'arbsk' => 'BhY',
			'arh' => '未测试动力装甲-H',
			'arhk' => 'DHPT',
			'arhe' => 3200,
			'arhs' => 1600,
			'arhsk' => 'bY',
			'ara' => '未测试动力装甲-A',
			'arak' => 'DAPT',
			'arae' => 3200,
			'aras' => 1600,
			'arask' => 'HY',
			'arf' => '未测试动力装甲-F',
			'arfk' => 'DFPT',
			'arfe' => 3200,
			'arfs' => 1600,
			'arfsk' => 'mY',
			'art' => 'Mr.Lein的终端机',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'x',
			'sub' => array
			(
				0 => array
				(
				'name' => 'Mr.Lein',
				'icon' => 0,
				'club' => 7,
				'wep' => '燃素粒子炮-高出力解放型',
				'wepk' => 'WJ',
				'wepe' => 3800,
				'weps' => 1500,
				'wepsk' => 'Nnufd',
				),
			),
		),
		88 => array
			(
			'mode' => 1,
			'num' => 4,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'rage' => 188,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 88,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'm',
			'pls' => 99,
			'mhp' => 8888888,
			'msp' => 888,
			'att' => 88888,
			'def' => 88888,
			'lvl' => 88,
			'skill' => 88888,
			'money' => 88888,
			'arb' => '[数据删除]',
			'arbk' => 'DB',
			'arbe' => 8888,
			'arbs' => 8888,
			'arbsk' => 'Aa',
			'arh' => '[数据删除]',
			'arhk' => 'DH',
			'arhe' => 8888,
			'arhs' => 8888,
			'arhsk' => 'Bb',
			'arf' => '[数据删除]',
			'arfk' => 'DF',
			'arfe' => 8888,
			'arfs' => 8888,
			'arfsk' => 'Mm',
			'ara' => '[数据删除]',
			'arak' => 'DA',
			'arae' => 8888,
			'aras' => 8888,
			'arask' => 'Hc',
			'art' => '[数据删除]',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'xH',
			'sub' => array
			(
				0 => array
				(
				'name' => 'SCP-682',
				'icon' => 103,
				'wep' => '[数据删除]',
				'wepk' => 'WN',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				),
				1 => array
				(
				'name' => 'SCP-173',
				'icon' => 98,
				'wep' => '[数据删除]',
				'wepk' => 'WF',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				),
				2 => array
				(
				'name' => 'SCP-076',
				'icon' => 98,
				'wep' => '[数据删除]',
				'wepk' => 'WK',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				),
				3 => array
				(
				'name' => 'SCP-958',
				'icon' => 98,
				'wep' => '[数据删除]',
				'wepk' => 'WG',
				'wepe' => 8888,
				'weps' => 8888,
				'wepsk' => 'nrd',
				),
			),
		),
	);
}

?>